// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=956d3c343790c16e9ae83a444024e2ecfd521255c35cbdc7fcad73e0a9a05f73
package c2db

var C2db_key_class_lut16 = [16]byte{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2}

func C2db_key_class32(in []byte, out []byte) {
	var v3 int
	var v10 byte
	for v3 = 0; v3 < 32; v3++ {
		v10 = in[v3] & 15
		out[v3] = C2db_key_class_lut16[v10]
	}
}
