// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=a1490faddc7d32ed3d9e83a3d8bb3c24fd7d906e30ee76384993b40a073356de
package c2db

type C2db_prefix_result_t struct {
	Slot_idx uint64
	Count    uint64
	Found    byte
}

func c2db_pref_bounds(page []byte, n uint64, addr uint64, len_ uint64) byte {
	var v11 bool
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	if uint64(len(page)) < len_ {
		len_ = uint64(len(page))
	}
	_ = 0
	if page == nil {
		return uint8(0)
	}
	v11 = (addr < n) && (len_ <= (n - addr))
	if v11 {
		return uint8(1)
	}
	return uint8(0)
}

func c2db_pref_read8(page []byte, n uint64, off uint64) byte {
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	if c2db_pref_bounds(page[:], n, off, uint64(1)) != 0 {
		return byte(page[off])
	}
	return uint8(0)
}

func c2db_pref_read16(page []byte, n uint64, off uint64) uint16 {
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	if c2db_pref_bounds(page[:], n, off, uint64(2)) != 0 {
		return uint16(uint16(page[off]) | (uint16(page[off+1]) << 8))
	}
	return 0
}

func c2db_pref_cmp(page []byte, n uint64, cell_key_off uint64, cell_klen uint64, pref []byte, plen uint64) int {
	var v6 uint64
	var v7 uint64
	var v8 byte
	var v9 byte
	var v20 bool
	var v28 bool
	v10 := uint64(0)
	_ = v10
	v7 = cell_klen
	if plen < v7 {
		v7 = plen
	}
	for v6 = 0; v6 < v7; v6++ {
		v8 = 0
		v9 = v8
		v20 = (cell_key_off < n) && (v6 < (n - cell_key_off))
		if v20 {
			v8 = page[cell_key_off+v6]
		}
		v28 = (pref != nil) && (v6 < plen)
		if v28 {
			v9 = pref[v10+v6]
		}
		if v8 < v9 {
			return -1
		}
		if v8 > v9 {
			return 1
		}
	}
	if cell_klen < plen {
		return -1
	}
	return 0
}

func C2db_btree_prefix_search(page []byte, n uint64, pref []byte, plen uint64) C2db_prefix_result_t {
	var v6 uint64
	var v7 uint64
	var v9 uint64
	var v10 uint64
	var v11 uint16
	var v12 int
	var v17 uint64
	var v39 uint64
	var v45 uint64
	var v84 []byte
	var v92 uint64
	v17 = 0
	var v4 C2db_prefix_result_t
	v4.Slot_idx = 0
	v4.Count = 0
	v4.Found = 0
	if (page == nil) || (n != 0x4000) {
		return v4
	}
	if ((pref == nil) || (plen == 0)) || (plen > 0xffff) {
		return v4
	}
	if c2db_pref_read8(page[v17:], n, uint64(20)) != 1 {
		return v4
	}
	v39 = uint64(c2db_pref_read16(page[v17:], n, 22))
	if v39 == 0 {
		return v4
	}
	v6 = 0
	v7 = v39
	for v6 < v7 {
		v45 = v6 + ((v7 - v6) / 2)
		v9 = 64 + (v45 * 2)
		if c2db_pref_bounds(page[v17:], n, v9, uint64(2)) == 0 {
			return v4
		}
		v10 = uint64(c2db_pref_read16(page[v17:], n, v9))
		if c2db_pref_bounds(page[v17:], n, v10, uint64(4)) == 0 {
			return v4
		}
		v11 = c2db_pref_read16(page[v17:], n, v10)
		if c2db_pref_bounds(page[v17:], n, (v10+4), uint64(v11)) == 0 {
			return v4
		}
		v12 = c2db_pref_cmp(page[v17:], n, (v10 + 4), uint64(v11), pref[:], plen)
		if v12 < 0 {
			v6 = v45 + 1
		} else {
			v7 = v45
		}
	}
	if v6 < v39 {
		v9 = 64 + (v6 * 2)
		v10 = uint64(c2db_pref_read16(page[v17:], n, v9))
		v84 = page[v17:]
		v11 = c2db_pref_read16(v84[:], n, v10)
		v12 = c2db_pref_cmp(v84[:], n, (v10 + 4), uint64(v11), pref[:], plen)
		if v12 == 0 {
			v4.Found = 1
			v4.Slot_idx = v6
			v4.Count = 1
			v92 = v6 + 1
			for v92 < v39 {
				v9 = 64 + (v92 * 2)
				if c2db_pref_bounds(page[v17:], n, v9, uint64(2)) == 0 {
					break
				}
				v10 = uint64(c2db_pref_read16(page[v17:], n, v9))
				if c2db_pref_bounds(page[v17:], n, v10, uint64(4)) == 0 {
					break
				}
				v11 = c2db_pref_read16(page[v17:], n, v10)
				if c2db_pref_bounds(page[v17:], n, (v10+4), uint64(v11)) == 0 {
					break
				}
				v12 = c2db_pref_cmp(page[v17:], n, (v10 + 4), uint64(v11), pref[:], plen)
				if v12 == 0 {
					v4.Count += 1
					v92++
				} else {
					break
				}
			}
		}
	}
	return v4
}
