// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=61ba09e6e036abce35f8e69c2b39d43ae2f12a2916b6c055b01a8fa189a4925a
package c2db

var C2db_wal_class_lut16 = [16]byte{0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0}

func C2db_wal_class32(in []byte, out []byte) {
	var v3 int
	var v10 byte
	for v3 = 0; v3 < 32; v3++ {
		v10 = in[v3] & 15
		out[v3] = C2db_wal_class_lut16[v10]
	}
}
