// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=4c4d676e80400da31f0cba7f325cd61b4a3b74f25759ac8236e296e7e96afd21
package c2db

type C2db_compact_result_t struct {
	Slots_before uint64
	Slots_after  uint64
	Bytes_freed  uint64
	Ok           byte
}

func c2db_pack_bounds(p []byte, n uint64, addr uint64, len_ uint64) byte {
	var v11 bool
	if uint64(len(p)) < n {
		n = uint64(len(p))
	}
	if uint64(len(p)) < len_ {
		len_ = uint64(len(p))
	}
	_ = 0
	if p == nil {
		return uint8(0)
	}
	v11 = (addr < n) && (len_ <= (n - addr))
	if v11 {
		return uint8(1)
	}
	return uint8(0)
}

func c2db_pack_read8(p []byte, n uint64, off uint64) byte {
	if uint64(len(p)) < n {
		n = uint64(len(p))
	}
	if c2db_pack_bounds(p[:], n, off, uint64(1)) != 0 {
		return byte(p[off])
	}
	return uint8(0)
}

func c2db_pack_write8(p []byte, n uint64, off uint64, val byte) {
	if uint64(len(p)) < n {
		n = uint64(len(p))
	}
	if c2db_pack_bounds(p[:], n, off, uint64(1)) != 0 {
		p[off] = val
	}
}

func c2db_pack_read16(p []byte, n uint64, off uint64) uint16 {
	if uint64(len(p)) < n {
		n = uint64(len(p))
	}
	if c2db_pack_bounds(p[:], n, off, uint64(2)) != 0 {
		return uint16(uint16(p[off]) | (uint16(p[off+1]) << 8))
	}
	return 0
}

func c2db_pack_write16(p []byte, n uint64, off uint64, val uint16) {
	var v8 uint16
	var v13 uint16
	if uint64(len(p)) < n {
		n = uint64(len(p))
	}
	if c2db_pack_bounds(p[:], n, off, uint64(2)) != 0 {
		v8 = val & 0xff
		p[off] = byte(v8)
		v13 = (val >> 8) & 0xff
		p[off+1] = byte(v13)
	}
}

func c2db_pack_copy(dst []byte, dn uint64, doff uint64, src []byte, sn uint64, soff uint64, len_ uint64) {
	var v7 uint64
	if c2db_pack_bounds(dst[:], dn, doff, len_) == 0 {
		return
	}
	if c2db_pack_bounds(src[:], sn, soff, len_) == 0 {
		return
	}
	for v7 = 0; v7 < len_; v7++ {
		dst[doff+v7] = src[soff+v7]
	}
}

func C2db_slot_pack_compact(page []byte, n uint64, scratch []byte, scratch_n uint64, idlen uint64, drop_tombstones byte) C2db_compact_result_t {
	var v10 uint64
	var v11 uint64
	var v12 uint64
	var v13 uint64
	var v21 uint64
	var v42 uint64
	var v46 uint64
	var v50 uint64
	var v73 byte
	var v77 uint64
	var v84 uint64
	var v91 uint64
	var v92 []byte
	var v96 uint64
	var v100 uint64
	var v114 uint64
	var v124 byte
	var v133 uint64
	v21 = 0
	var v6 C2db_compact_result_t
	v6.Slots_before = 0
	v6.Slots_after = 0
	v6.Bytes_freed = 0
	v6.Ok = 0
	if (page == nil) || (n != 0x4000) {
		return v6
	}
	if (scratch == nil) || (scratch_n < 0x4000) {
		return v6
	}
	if c2db_pack_read8(page[v21:], n, uint64(20)) != 1 {
		return v6
	}
	v42 = uint64(c2db_pack_read16(page[v21:], n, 22))
	v43 := page[v21:]
	v46 = uint64(c2db_pack_read16(v43[:], n, 24))
	v50 = uint64(c2db_pack_read16(v43[:], n, 26))
	if ((v46 > 0x4000) || (v50 > 0x4000)) || (v46 > v50) {
		return v6
	}
	c2db_pack_copy(scratch[v21:], scratch_n, uint64(0), page[v21:], n, uint64(0), uint64(0x4000))
	v10 = 64
	v11 = 0x4000
	v12 = 0
	for v13 = v12; v13 < v42; v13++ {
		v77 = 64 + (v13 * 2)
		if c2db_pack_bounds(scratch[v21:], scratch_n, v77, uint64(2)) == 0 {
			return v6
		}
		v84 = uint64(c2db_pack_read16(scratch[v21:], scratch_n, v77))
		if c2db_pack_bounds(scratch[v21:], scratch_n, v84, uint64(4)) == 0 {
			return v6
		}
		v91 = uint64(c2db_pack_read16(scratch[v21:], scratch_n, v84))
		v92 = scratch[v21:]
		v96 = uint64(c2db_pack_read16(v92[:], scratch_n, (v84 + 2)))
		v100 = ((4 + v91) + idlen) + v96
		if c2db_pack_bounds(v92[:], scratch_n, v84, v100) == 0 {
			return v6
		}
		v73 = 0
		if drop_tombstones != 0 {
			if v96 == 0 {
				v73 = 1
			} else {
				if idlen == 16 {
					v114 = ((v84 + 4) + v91) + 8
					if c2db_pack_bounds(scratch[v21:], scratch_n, v114, uint64(1)) != 0 {
						v124 = scratch[v21+v114] & 63
						if byte(uint32(v124)>>2) == 1 {
							v73 = 1
						}
					}
				}
			}
		}
		if v73 == 0 {
			if v100 > v11 {
				return v6
			}
			v133 = v11 - v100
			if (v10 + 2) > v133 {
				return v6
			}
			c2db_pack_copy(page[v21:], n, v133, scratch[v21:], scratch_n, v84, v100)
			c2db_pack_write16(page[v21:], n, (uint64(64) + (v12 * 2)), uint16(v133))
			v10 += 2
			v11 = v133
			v12++
		}
	}
	c2db_pack_write16(page[v21:], n, uint64(22), uint16(v12))
	v156 := page[v21:]
	c2db_pack_write16(v156[:], n, uint64(24), uint16(v10))
	c2db_pack_write16(v156[:], n, uint64(26), uint16(v11))
	v164 := v50 - v46
	v165 := v11 - v10
	if v165 >= v164 {
		v6.Bytes_freed = v165 - v164
	} else {
		v6.Bytes_freed = 0
	}
	v6.Slots_before = v42
	v6.Slots_after = v12
	v6.Ok = 1
	return v6
}
