// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=18d6c31b756c429d2f076cde927ed8c68958ab1628515f7e2650cb152579a8a1
package c2db

func C2db_slot_occ32(p []byte) uint32 {
	var v1 uint32
	var v2 uint32
	if p == nil {
		return 0
	}
	v1 = 0
	for v2 = v1; v2 < 32; v2++ {
		if p[v2+0] != 0 {
			v1++
		}
	}
	return v1
}
