// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=24f46ebb75a976d033124904b2223b699e2f764fcca01e0d70308f3be97026a7
package c2db

type C2db_zip_entry_t struct {
	Key     uint64
	Ver     uint64
	Val_crc uint32
	Deleted byte
	_pad    [3]byte
}

type C2db_zip_result_t struct {
	Merged_count    uint64
	Conflicts_count uint64
	Ok              byte
}

func C2db_zipper_3way(base []C2db_zip_entry_t, n_base uint64, ours []C2db_zip_entry_t, n_ours uint64, theirs []C2db_zip_entry_t, n_theirs uint64, out []C2db_zip_entry_t, cap_ uint64) C2db_zip_result_t {
	var v9 uint64
	var v10 uint64
	var v11 uint64
	var v12 uint64
	var v13 uint64
	var v17 uint64
	var v23 bool
	var v31 bool
	var v39 bool
	var v47 bool
	var v59 uint64
	var v60 byte
	var v61 byte
	var v62 byte
	var v64 byte
	var v122 bool
	var v125 bool
	var v159 bool
	var v162 bool
	var v169 bool
	var v172 bool
	var v179 bool
	var v182 bool
	var v183 byte
	var v184 byte
	var v223 bool
	var v230 bool
	var v237 bool
	var v273 bool
	var v276 bool
	var v277 byte
	var v305 bool
	var v308 bool
	var v309 byte
	v17 = 0
	var v8 C2db_zip_result_t
	v8.Merged_count = 0
	v8.Conflicts_count = 0
	v8.Ok = 1
	v23 = (out == nil) && (cap_ > 0)
	if v23 {
		v8.Ok = 0
		return v8
	}
	v31 = (base == nil) && (n_base > 0)
	if v31 {
		v8.Ok = 0
		return v8
	}
	v39 = (ours == nil) && (n_ours > 0)
	if v39 {
		v8.Ok = 0
		return v8
	}
	v47 = (theirs == nil) && (n_theirs > 0)
	if v47 {
		v8.Ok = 0
		return v8
	}
	v9 = 0
	v10 = v9
	v11 = v10
	v12 = v11
	v13 = v12
	for {
		v54 := v9 < n_base
		if !((v54 || (v10 < n_ours)) || (v11 < n_theirs)) {
			break
		}
		var v63 C2db_zip_entry_t
		v59 = 0xffffffffffffffff
		if v54 {
			if base[v17+v9].Key < v59 {
				v59 = base[v17+v9].Key
			}
		}
		if v10 < n_ours {
			if ours[v17+v10].Key < v59 {
				v59 = ours[v17+v10].Key
			}
		}
		if v11 < n_theirs {
			if theirs[v17+v11].Key < v59 {
				v59 = theirs[v17+v11].Key
			}
		}
		v60 = 0
		if v9 < n_base {
			if base[v17+v9].Key == v59 {
				v60 = 1
			}
		}
		v61 = 0
		if v10 < n_ours {
			if ours[v17+v10].Key == v59 {
				v61 = 1
			}
		}
		v62 = 0
		if v11 < n_theirs {
			if theirs[v17+v11].Key == v59 {
				v62 = 1
			}
		}
		v64 = 1
		v122 = (v60 == 0) && (v61 != 0)
		v125 = v122 && (v62 != 0)
		if v125 {
			var cond_140 bool
			if ours[v17+v10].Val_crc == theirs[v17+v11].Val_crc {
				if ours[v17+v10].Deleted == theirs[v17+v11].Deleted {
					cond_140 = true
				}
			}
			if cond_140 {
				v63 = ours[v17+v10]
			} else {
				v13++
				if ours[v17+v10].Ver > theirs[v17+v11].Ver {
					v63 = ours[v17+v10]
				} else {
					v63 = theirs[v17+v11]
				}
			}
		} else {
			v159 = (v60 == 0) && (v61 != 0)
			v162 = v159 && (v62 == 0)
			if v162 {
				v63 = ours[v17+v10]
			} else {
				v169 = (v60 == 0) && (v61 == 0)
				v172 = v169 && (v62 != 0)
				if v172 {
					v63 = theirs[v17+v11]
				} else {
					v179 = (v60 != 0) && (v61 != 0)
					v182 = v179 && (v62 != 0)
					if v182 {
						v183 = 0
						if (ours[v17+v10].Val_crc != base[v17+v9].Val_crc) || (ours[v17+v10].Deleted != base[v17+v9].Deleted) {
							v183 = 1
						}
						v184 = 0
						if (theirs[v17+v11].Val_crc != base[v17+v9].Val_crc) || (theirs[v17+v11].Deleted != base[v17+v9].Deleted) {
							v184 = 1
						}
						v223 = (v183 == 0) && (v184 == 0)
						if v223 {
							v63 = base[v17+v9]
						} else {
							v230 = (v183 != 0) && (v184 == 0)
							if v230 {
								v63 = ours[v17+v10]
							} else {
								v237 = (v183 == 0) && (v184 != 0)
								if v237 {
									v63 = theirs[v17+v11]
								} else {
									var cond_254 bool
									if ours[v17+v10].Val_crc == theirs[v17+v11].Val_crc {
										if ours[v17+v10].Deleted == theirs[v17+v11].Deleted {
											cond_254 = true
										}
									}
									if cond_254 {
										v63 = ours[v17+v10]
									} else {
										v13++
										if ours[v17+v10].Ver > theirs[v17+v11].Ver {
											v63 = ours[v17+v10]
										} else {
											v63 = theirs[v17+v11]
										}
									}
								}
							}
						}
					} else {
						v273 = (v60 != 0) && (v61 != 0)
						v276 = v273 && (v62 == 0)
						if v276 {
							v277 = 0
							if (ours[v17+v10].Val_crc != base[v17+v9].Val_crc) || (ours[v17+v10].Deleted != base[v17+v9].Deleted) {
								v277 = 1
							}
							if v277 == 0 {
								v64 = 0
							} else {
								v13++
								v63 = ours[v17+v10]
							}
						} else {
							v305 = (v60 != 0) && (v61 == 0)
							v308 = v305 && (v62 != 0)
							if v308 {
								v309 = 0
								if (theirs[v17+v11].Val_crc != base[v17+v9].Val_crc) || (theirs[v17+v11].Deleted != base[v17+v9].Deleted) {
									v309 = 1
								}
								if v309 == 0 {
									v64 = 0
								} else {
									v13++
									v63 = theirs[v17+v11]
								}
							} else {
								v64 = 0
							}
						}
					}
				}
			}
		}
		if v64 != 0 {
			if v12 >= cap_ {
				v8.Ok = 0
				v8.Merged_count = v12
				v8.Conflicts_count = v13
				return v8
			}
			out[v17+v12] = v63
			v12++
		}
		if v60 != 0 {
			v9++
		}
		if v61 != 0 {
			v10++
		}
		if v62 != 0 {
			v11++
		}
	}
	v8.Merged_count = v12
	v8.Conflicts_count = v13
	v8.Ok = 1
	return v8
}
