//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=1d87eabacd2ca911121047a851c94f236eb1bdc13b7ab6d1c1a829d15023af5a
package c2db

import "simd/archsimd"

var C2db_wal_class_lut16_avx2 = [16]byte{0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0}

func C2db_wal_class32_avx2(in []byte, out []byte) {
	mm256_broadcastsi128_si256(archsimd.LoadUint8x16(C2db_wal_class_lut16_avx2[0:16])).PermuteOrZeroGrouped(archsimd.LoadUint8x32(in[0:32]).And(archsimd.BroadcastUint8x32(byte(15))).AsInt8x32()).Store(out[0:32])
}

func mm256_broadcastsi128_si256(v archsimd.Uint8x16) archsimd.Uint8x32 {
	var a [32]byte
	v.Store(a[:16])
	v.Store(a[16:])
	return archsimd.LoadUint8x32Array(&a)
}
