//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=57644d6fb11a44aed010ee5c9fcd6771a82ec34af7ca7e7d59baf208005c5117
package c2db

import (
	"math/bits"
	"simd/archsimd"
)

func C2db_slot_occ32_avx2(p []byte) uint32 {
	if p == nil {
		return 0
	}
	return uint32(uint32(32) - uint32(bits.OnesCount32(uint32(archsimd.LoadUint8x32(p[0:32]).Equal(archsimd.BroadcastUint8x32(byte(0))).ToBits()))))
}
