// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=4f218c2f0014a3f6ff07f956b1a08f3986ed0e099f41fe40987dd0ead0655300
package c2db

type Db_bt_state_t struct {
	Nkeys  uint64
	Ok     byte
	Copied byte
}

type Db_bt_get_t struct {
	Len_     uint64
	Walked   uint64
	Found    byte
	Fallback byte
}

type Db_bt_heap_st_t struct {
	Root  uint64
	Used  uint64
	Nkeys uint64
	Pages uint64
	Ok    byte
	Full  byte
}

type Db_bt_scan_t struct {
	Nfound uint64
	Ok     byte
}

func bt_bounds(page []byte, n uint64, addr uint64, len_ uint64) byte {
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	if uint64(len(page)) < len_ {
		len_ = uint64(len(page))
	}
	_ = 0
	if page == nil {
		return uint8(0)
	}
	if n != 0x4000 {
		return uint8(0)
	}
	v14 := (addr < n) && (len_ <= (n - addr))
	if v14 {
		return uint8(1)
	}
	return uint8(0)
}

func bt_read8(page []byte, n uint64, addr uint64) byte {
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	if page == nil {
		return uint8(0)
	}
	v11 := (addr < n) && (1 <= (n - addr))
	if v11 {
		return byte(page[addr+0])
	}
	return uint8(0)
}

func bt_read16(page []byte, n uint64, addr uint64) uint16 {
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	v3 := uint64(0)
	if page == nil {
		return 0
	}
	v11 := (addr < n) && (2 <= (n - addr))
	if v11 {
		return uint16(uint16(page[v3+addr]) | (uint16(page[v3+addr+1]) << 8))
	}
	return 0
}

func bt_write8(page []byte, n uint64, addr uint64, val byte) {
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	if page == nil {
		return
	}
	v11 := (addr < n) && (1 <= (n - addr))
	if v11 {
		page[addr+0] = val
	}
}

func bt_write16(page []byte, n uint64, addr uint64, val uint16) {
	var v13 uint16
	var v19 uint16
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	v4 := uint64(0)
	if page == nil {
		return
	}
	v11 := (addr < n) && (2 <= (n - addr))
	if v11 {
		v13 = val & 0xff
		page[v4+addr] = byte(v13)
		v19 = (val >> 8) & 0xff
		page[v4+addr+1] = byte(v19)
	}
}

func bt_write32(page []byte, n uint64, addr uint64, val uint32) {
	var v13 uint32
	var v19 uint64
	var v27 uint64
	var v35 uint64
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	v4 := uint64(0)
	if page == nil {
		return
	}
	v11 := (addr < n) && (4 <= (n - addr))
	if v11 {
		v13 = val & 0xff
		page[v4+addr] = byte(v13)
		v19 = uint64(uint64(val)>>8) & 0xff
		page[v4+addr+1] = byte(v19)
		v27 = uint64(uint64(val)>>16) & 0xff
		page[v4+addr+2] = byte(v27)
		v35 = uint64(uint64(val)>>24) & 0xff
		page[v4+addr+3] = byte(v35)
	}
}

func bt_read64(page []byte, n uint64, addr uint64) uint64 {
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	v3 := uint64(0)
	if page == nil {
		return 0
	}
	v11 := (addr < n) && (8 <= (n - addr))
	if v11 {
		return uint64(((((((uint64(page[v3+addr]) | uint64(uint64(page[v3+addr+1])<<8)) | uint64(uint64(page[v3+addr+2])<<16)) | uint64(uint64(page[v3+addr+3])<<24)) | uint64(uint64(page[v3+addr+4])<<32)) | uint64(uint64(page[v3+addr+5])<<40)) | uint64(uint64(page[v3+addr+6])<<48)) | uint64(uint64(page[v3+addr+7])<<56))
	}
	return 0
}

func bt_write64(page []byte, n uint64, addr uint64, val uint64) {
	var v13 uint64
	var v19 uint64
	var v27 uint64
	var v35 uint64
	var v43 uint64
	var v51 uint64
	var v59 uint64
	var v67 uint64
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	v4 := uint64(0)
	if page == nil {
		return
	}
	v11 := (addr < n) && (8 <= (n - addr))
	if v11 {
		v13 = val & 0xff
		page[v4+addr] = byte(v13)
		v19 = uint64(val>>8) & 0xff
		page[v4+addr+1] = byte(v19)
		v27 = uint64(val>>16) & 0xff
		page[v4+addr+2] = byte(v27)
		v35 = uint64(val>>24) & 0xff
		page[v4+addr+3] = byte(v35)
		v43 = uint64(val>>32) & 0xff
		page[v4+addr+4] = byte(v43)
		v51 = uint64(val>>40) & 0xff
		page[v4+addr+5] = byte(v51)
		v59 = uint64(val>>48) & 0xff
		page[v4+addr+6] = byte(v59)
		v67 = uint64(val>>56) & 0xff
		page[v4+addr+7] = byte(v67)
	}
}

func bt_copy_bytes(dst []byte, dn uint64, doff uint64, src []byte, sn uint64, soff uint64, len_ uint64) {
	var v7 uint64
	var v17 bool
	var v21 bool
	if (dst == nil) || (src == nil) {
		return
	}
	for v7 = 0; v7 < len_; v7++ {
		v17 = (doff < dn) && (v7 < (dn - doff))
		if v17 {
			v21 = (soff < sn) && (v7 < (sn - soff))
			if v21 {
				dst[doff+v7] = src[soff+v7]
			}
		}
	}
}

func bt_cow(pub []byte, dirty []byte, n uint64) {
	if (pub == nil) || (dirty == nil) {
		return
	}
	if n == 0 {
		return
	}
	copy(dirty[:][:n], pub[:][:n])
}

func bt_cow_page(pub []byte, dirty []byte, nbytes uint64, pg uint64, mask uint64) uint64 {
	if (pub == nil) || (dirty == nil) {
		return mask
	}
	v13 := pg * 0x4000
	if v13 >= nbytes {
		return mask
	}
	if 0x4000 > (nbytes - v13) {
		return mask
	}
	if pg >= 64 {
		copy(dirty[v13:][:16384], pub[v13:][:16384])
		return mask
	}
	v24 := uint64(1 << byte(pg))
	v25 := mask & v24
	if v25 != 0 {
		return mask
	}
	copy(dirty[v13:][:16384], pub[v13:][:16384])
	return uint64(mask | v24)
}

func bt_copy_in(page []byte, n uint64, addr uint64, src []byte, len_ uint64) {
	var v5 uint64
	var v15 bool
	if (page == nil) || (src == nil) {
		return
	}
	for v5 = 0; v5 < len_; v5++ {
		v15 = (addr < n) && (v5 < (n - addr))
		if v15 {
			page[addr+v5] = src[v5]
		}
	}
}

func bt_copy_out(page []byte, n uint64, addr uint64, dst []byte, len_ uint64) {
	var v5 uint64
	var v15 bool
	if (page == nil) || (dst == nil) {
		return
	}
	for v5 = 0; v5 < len_; v5++ {
		v15 = (addr < n) && (v5 < (n - addr))
		if v15 {
			dst[v5] = page[addr+v5]
		}
	}
}

func bt_keyeq(page []byte, n uint64, koff uint64, klen uint64, key []byte) byte {
	var v5 uint64
	var v19 bool
	if (page == nil) || (key == nil) {
		return uint8(0)
	}
	for v5 = 0; v5 < klen; v5++ {
		v14 := koff + v5
		v19 = (v14 < n) && (1 <= (n - v14))
		if v19 {
			if page[v14] != key[v5] {
				return uint8(0)
			}
		} else {
			return uint8(0)
		}
	}
	return uint8(1)
}

func bt_keycmp(a []byte, alen uint64, b []byte, blen uint64) int32 {
	var v4 uint64
	var v5 uint64
	var v6 byte
	var v7 byte
	if uint64(len(a)) < alen {
		alen = uint64(len(a))
	}
	if uint64(len(b)) < blen {
		blen = uint64(len(b))
	}
	v11 := uint64(0)
	v4 = alen
	if blen < v4 {
		v4 = blen
	}
	for v5 = 0; v5 < v4; v5++ {
		v6 = 0
		v7 = v6
		if a != nil {
			v6 = a[v11+v5]
		}
		if b != nil {
			v7 = b[v11+v5]
		}
		if v6 < v7 {
			return -1
		}
		if v6 > v7 {
			return 1
		}
	}
	if alen < blen {
		return -1
	}
	if alen > blen {
		return 1
	}
	return 0
}

func bt_keycmp_at(page []byte, n uint64, aoff uint64, alen uint64, b []byte, blen uint64) int32 {
	var v6 uint64
	var v7 uint64
	var v8 byte
	var v9 byte
	var v19 bool
	if uint64(len(b)) < blen {
		blen = uint64(len(b))
	}
	v13 := uint64(0)
	v6 = alen
	if blen < v6 {
		v6 = blen
	}
	for v7 = 0; v7 < v6; v7++ {
		v8 = 0
		v9 = v8
		if page != nil {
			v19 = (aoff < n) && (v7 < (n - aoff))
			if v19 {
				v8 = page[v13+aoff+v7]
			}
		}
		if b != nil {
			v9 = b[v13+v7]
		}
		if v8 < v9 {
			return -1
		}
		if v8 > v9 {
			return 1
		}
	}
	if alen < blen {
		return -1
	}
	if alen > blen {
		return 1
	}
	return 0
}

func bt_keycmp_pp(page []byte, n uint64, aoff uint64, alen uint64, boff uint64, blen uint64) int32 {
	var v6 uint64
	var v7 uint64
	var v8 byte
	var v9 byte
	var v19 bool
	var v26 bool
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	if uint64(len(page)) < alen {
		alen = uint64(len(page))
	}
	if uint64(len(page)) < blen {
		blen = uint64(len(page))
	}
	v13 := uint64(0)
	v6 = alen
	if blen < v6 {
		v6 = blen
	}
	for v7 = 0; v7 < v6; v7++ {
		v8 = 0
		v9 = v8
		if page != nil {
			v19 = (aoff < n) && (v7 < (n - aoff))
			if v19 {
				v8 = page[v13+aoff+v7]
			}
			v26 = (boff < n) && (v7 < (n - boff))
			if v26 {
				v9 = page[v13+boff+v7]
			}
		}
		if v8 < v9 {
			return -1
		}
		if v8 > v9 {
			return 1
		}
	}
	if alen < blen {
		return -1
	}
	if alen > blen {
		return 1
	}
	return 0
}

func bt_find(page []byte, n uint64, key []byte, klen uint64) uint64 {
	var v5 uint64
	v11 := uint64(bt_read16(page[:], n, uint64(22)))
	for v5 = 0; v5 < v11; v5++ {
		v16 := uint64(64) + (v5 * 2)
		if bt_bounds(page[:], n, v16, uint64(2)) == 0 {
			return v11
		}
		v21 := uint64(bt_read16(page[:], n, v16))
		if bt_bounds(page[:], n, v21, uint64(4)) != 0 {
			if uint64(bt_read16(page[:], n, v21)) == klen {
				if bt_keyeq(page[:], n, (v21+4), klen, key[:]) != 0 {
					return v5
				}
			}
		}
	}
	return v11
}

func bt_off_ok(n uint64, base uint64, off uint64, len_ uint64) byte {
	if off >= 0x4000 {
		return uint8(0)
	}
	if len_ > (uint64(0x4000) - off) {
		return uint8(0)
	}
	if base >= n {
		return uint8(0)
	}
	if 0x4000 > (n - base) {
		return uint8(0)
	}
	v14 := base + off
	v18 := (v14 < n) && (len_ <= (n - v14))
	if v18 {
		return uint8(1)
	}
	return uint8(0)
}

func bt_find_at(heap []byte, n uint64, base uint64, key []byte, klen uint64) uint64 {
	var v6 uint64
	v13 := uint64(bt_read16(heap[:], n, (base + 22)))
	for v6 = 0; v6 < v13; v6++ {
		v18 := uint64(64) + (v6 * 2)
		if bt_off_ok(n, base, v18, uint64(2)) == 0 {
			return v13
		}
		v24 := uint64(bt_read16(heap[:], n, (base + v18)))
		if bt_off_ok(n, base, v24, uint64(4)) != 0 {
			if uint64(bt_read16(heap[:], n, (base+v24))) == klen {
				if bt_keyeq(heap[:], n, ((base+v24)+4), klen, key[:]) != 0 {
					return v6
				}
			}
		}
	}
	return v13
}

func bt_get_at(heap []byte, n uint64, base uint64, key []byte, klen uint64, out []byte, outn uint64) Db_bt_get_t {
	var v14 uint64
	v20 := uint64(0)
	var v7 Db_bt_get_t
	v7.Len_ = 0
	v7.Walked = 0
	v7.Found = 0
	v7.Fallback = 0
	if heap == nil {
		return v7
	}
	if ((key == nil) || (klen == 0)) || (klen > 0xffff) {
		return v7
	}
	if bt_read8(heap[v20:], n, (base+20)) != 1 {
		return v7
	}
	v36 := heap[v20:]
	v42 := bt_find_at(v36[:], n, base, key[:], klen)
	if v42 >= uint64(bt_read16(v36[:], n, (base+22))) {
		return v7
	}
	v46 := uint64(64) + (v42 * 2)
	if bt_off_ok(n, base, v46, uint64(2)) == 0 {
		return v7
	}
	v53 := uint64(bt_read16(heap[v20:], n, (base + v46)))
	if bt_off_ok(n, base, v53, uint64(4)) == 0 {
		return v7
	}
	v57 := heap[v20:]
	v58 := base + v53
	v59 := bt_read16(v57[:], n, v58)
	v64 := bt_read16(v57[:], n, (v58 + 2))
	if uint64(v59) != klen {
		return v7
	}
	if bt_off_ok(n, base, v53, ((uint64(4)+uint64(v59))+uint64(v64))) == 0 {
		return v7
	}
	v73 := uint64(v64)
	v7.Len_ = v73
	v7.Found = 1
	v14 = v73
	if v14 > outn {
		v14 = outn
	}
	v82 := (out != nil) && (v14 > 0)
	if v82 {
		bt_copy_out(heap[v20:], n, (((base + v53) + 4) + uint64(v59)), out[v20:], v14)
	}
	return v7
}

func bt_insert_at(heap []byte, n uint64, base uint64, key []byte, klen uint64, val []byte, vlen uint64) Db_bt_state_t {
	var v8 uint64
	var v12 uint64
	var v17 uint64
	var v114 []byte
	v22 := uint64(0)
	var v7 Db_bt_state_t
	v7.Nkeys = 0
	v7.Ok = 0
	v7.Copied = 0
	if heap == nil {
		return v7
	}
	if ((klen == 0) || (klen > 0xffff)) || (vlen > 0xffff) {
		return v7
	}
	if key == nil {
		return v7
	}
	v40 := (vlen > 0) && (val == nil)
	if v40 {
		return v7
	}
	if bt_read8(heap[v22:], n, (base+20)) != 1 {
		return v7
	}
	v46 := heap[v22:]
	v8 = uint64(bt_read16(v46[:], n, (base + 22)))
	v55 := uint64(bt_read16(v46[:], n, (base + 24)))
	v60 := uint64(bt_read16(v46[:], n, (base + 26)))
	v7.Nkeys = v8
	if v55 < 64 {
		return v7
	}
	if v60 > 0x4000 {
		return v7
	}
	if v55 > v60 {
		return v7
	}
	v65 := (uint64(4) + klen) + vlen
	v68 := bt_find_at(heap[v22:], n, base, key[v22:], klen)
	if v68 < v8 {
		v12 = v55
		v17 = v68
	} else {
		if v55 >= 0x4000 {
			return v7
		}
		if 2 > (uint64(0x4000) - v55) {
			return v7
		}
		v12 = v55 + 2
		v17 = v8
	}
	if v65 > v60 {
		return v7
	}
	v75 := v60 - v65
	if v12 > v75 {
		return v7
	}
	v79 := uint64(64) + (v17 * 2)
	if bt_off_ok(n, base, v75, v65) == 0 {
		return v7
	}
	if bt_off_ok(n, base, v79, uint64(2)) == 0 {
		return v7
	}
	v85 := heap[v22:]
	v86 := base + v75
	bt_write16(v85[:], n, v86, uint16(klen))
	bt_write16(v85[:], n, (v86 + 2), uint16(vlen))
	bt_copy_in(v85[:], n, (v86 + 4), key[v22:], klen)
	if vlen > 0 {
		bt_copy_in(heap[v22:], n, (((base + v75) + 4) + klen), val[:], vlen)
	}
	bt_write16(heap[v22:], n, (base + v79), uint16(v75))
	if v68 >= v8 {
		v8++
		v114 = heap[v22:]
		bt_write16(v114[:], n, (base + 22), uint16(v8))
		bt_write16(v114[:], n, (base + 24), uint16(v12))
	}
	bt_write16(heap[v22:], n, (base + 26), uint16(v75))
	v7.Nkeys = v8
	v7.Ok = 1
	return v7
}

func Db_bt_leaf_init(page []byte, n uint64) Db_bt_state_t {
	v6 := uint64(0)
	var v2 Db_bt_state_t
	v2.Nkeys = 0
	v2.Ok = 0
	v2.Copied = 0
	if (page == nil) || (n != 0x4000) {
		return v2
	}
	if bt_bounds(page[v6:], n, uint64(20), uint64(1)) == 0 {
		return v2
	}
	if bt_bounds(page[v6:], n, uint64(22), uint64(6)) == 0 {
		return v2
	}
	v23 := page[v6:]
	bt_write8(v23[:], n, uint64(20), uint8(1))
	bt_write16(v23[:], n, uint64(22), uint16(0))
	bt_write16(v23[:], n, uint64(24), uint16(64))
	bt_write16(v23[:], n, uint64(26), uint16(0x4000))
	v2.Ok = 1
	return v2
}

func Db_bt_insert(pub []byte, dirty []byte, n uint64, st *Db_bt_state_t, key []byte, klen uint64, val []byte, vlen uint64) Db_bt_state_t {
	var v9 uint64
	var v13 uint64
	var v18 uint64
	v41 := uint64(0)
	var v8 Db_bt_state_t
	v8.Nkeys = 0
	v8.Ok = 0
	v8.Copied = 0
	if ((pub == nil) || (dirty == nil)) || (n != 0x4000) {
		return v8
	}
	bt_cow(pub[:], dirty[:], n)
	v8.Copied = 1
	if ((klen == 0) || (klen > 0xffff)) || (vlen > 0xffff) {
		return v8
	}
	if key == nil {
		return v8
	}
	v48 := (vlen > 0) && (val == nil)
	if v48 {
		return v8
	}
	if bt_read8(dirty[:], n, uint64(20)) != 1 {
		return v8
	}
	v9 = uint64(bt_read16(dirty[:], n, 22))
	v57 := uint64(bt_read16(dirty[:], n, uint64(24)))
	v60 := uint64(bt_read16(dirty[:], n, uint64(26)))
	v8.Nkeys = v9
	if v57 < 64 {
		return v8
	}
	if v60 > n {
		return v8
	}
	if v57 > v60 {
		return v8
	}
	v64 := (uint64(4) + klen) + vlen
	v66 := bt_find(dirty[:], n, key[v41:], klen)
	if v66 < v9 {
		v13 = v57
		v18 = v66
	} else {
		if v57 >= n {
			return v8
		}
		if 2 > (n - v57) {
			return v8
		}
		v13 = v57 + 2
		v18 = v9
	}
	if v64 > v60 {
		return v8
	}
	v71 := v60 - v64
	if v13 > v71 {
		return v8
	}
	v75 := uint64(64) + (v18 * 2)
	if bt_bounds(dirty[:], n, v71, v64) == 0 {
		return v8
	}
	if bt_bounds(dirty[:], n, v75, uint64(2)) == 0 {
		return v8
	}
	bt_write16(dirty[:], n, v71, uint16(klen))
	bt_write16(dirty[:], n, (v71 + 2), uint16(vlen))
	bt_copy_in(dirty[:], n, (v71 + 4), key[v41:], klen)
	if vlen > 0 {
		bt_copy_in(dirty[:], n, ((v71 + 4) + klen), val[:], vlen)
	}
	bt_write16(dirty[:], n, v75, uint16(v71))
	if v66 >= v9 {
		v9++
		bt_write16(dirty[:], n, uint64(22), uint16(v9))
		bt_write16(dirty[:], n, uint64(24), uint16(v13))
	}
	bt_write16(dirty[:], n, uint64(26), uint16(v71))
	v8.Nkeys = v9
	v8.Ok = 1
	return v8
}

func Db_bt_get(page []byte, n uint64, key []byte, klen uint64, out []byte, outn uint64) Db_bt_get_t {
	var v13 uint64
	v19 := uint64(0)
	var v6 Db_bt_get_t
	v6.Len_ = 0
	v6.Walked = 0
	v6.Found = 0
	v6.Fallback = 0
	if (page == nil) || (n != 0x4000) {
		return v6
	}
	if ((key == nil) || (klen == 0)) || (klen > 0xffff) {
		return v6
	}
	if bt_read8(page[v19:], n, uint64(20)) != 1 {
		return v6
	}
	v38 := page[v19:]
	v43 := bt_find(v38[:], n, key[:], klen)
	if v43 >= uint64(bt_read16(v38[:], n, uint64(22))) {
		return v6
	}
	v47 := uint64(64) + (v43 * 2)
	if bt_bounds(page[v19:], n, v47, uint64(2)) == 0 {
		return v6
	}
	v52 := page[v19:]
	v54 := uint64(bt_read16(v52[:], n, v47))
	if bt_bounds(v52[:], n, v54, uint64(4)) == 0 {
		return v6
	}
	v59 := page[v19:]
	v60 := bt_read16(v59[:], n, v54)
	v64 := bt_read16(v59[:], n, (v54 + 2))
	if uint64(v60) != klen {
		return v6
	}
	if bt_bounds(page[v19:], n, v54, ((uint64(4)+uint64(v60))+uint64(v64))) == 0 {
		return v6
	}
	v6.Len_ = uint64(v64)
	v6.Found = 1
	v13 = uint64(v64)
	if v13 > outn {
		v13 = outn
	}
	v83 := (out != nil) && (v13 > 0)
	if v83 {
		bt_copy_out(page[v19:], n, ((v54 + 4) + uint64(v60)), out[v19:], v13)
	}
	return v6
}

func bt_leaf_repack(page []byte, n uint64, idlen uint64) byte {
	var v5 uint64
	if uint64(len(page)) < idlen {
		idlen = uint64(len(page))
	}
	v18 := uint64(0)
	var v3 [16384]byte
	if (page == nil) || (n != 0x4000) {
		return uint8(0)
	}
	v26 := page[v18:]
	copy(v3[:][:16384], v26[:][:16384])
	if Db_bt_leaf_init(v26[:], uint64(0x4000)).Ok == 0 {
		copy(page[v18:][:16384], v3[:][:16384])
		return uint8(0)
	}
	v48 := page[v18:]
	bt_write8(v48[:], n, uint64(20), bt_read8(v3[:], uint64(0x4000), uint64(20)))
	bt_write64(v48[:], n, uint64(8), bt_read64(v3[:], uint64(0x4000), uint64(8)))
	v5 = 0
	for v5 < uint64(bt_read16(v3[:], uint64(0x4000), uint64(22))) {
		v61 := uint64(bt_read16(v3[:], uint64(0x4000), (uint64(64) + (v5 * 2))))
		if bt_bounds(v3[:], uint64(0x4000), v61, uint64(4)) == 0 {
			copy(page[v18:][:16384], v3[:][:16384])
			return uint8(0)
		}
		v81 := ((uint64(4) + uint64(bt_read16(v3[:], uint64(0x4000), v61))) + idlen) + uint64(bt_read16(v3[:], uint64(0x4000), (v61+2)))
		if bt_bounds(v3[:], uint64(0x4000), v61, v81) == 0 {
			copy(page[v18:][:16384], v3[:][:16384])
			return uint8(0)
		}
		v89 := page[v18:]
		v92 := uint64(bt_read16(v89[:], n, uint64(24)))
		v96 := uint64(bt_read16(v89[:], n, uint64(26)))
		if v92 >= 0x4000 {
			copy(page[v18:][:16384], v3[:][:16384])
			return uint8(0)
		}
		if 2 > (uint64(0x4000) - v92) {
			copy(page[v18:][:16384], v3[:][:16384])
			return uint8(0)
		}
		if v81 > v96 {
			copy(page[v18:][:16384], v3[:][:16384])
			return uint8(0)
		}
		v113 := v96 - v81
		if (v92 + 2) > v113 {
			copy(page[v18:][:16384], v3[:][:16384])
			return uint8(0)
		}
		v120 := page[v18:]
		bt_copy_bytes(v120[:], n, v113, v3[:], uint64(0x4000), v61, v81)
		v128 := uint16(v113)
		bt_write16(v120[:], n, (uint64(64) + (v5 * 2)), v128)
		v133 := v5 + 1
		bt_write16(v120[:], n, uint64(22), uint16(v133))
		bt_write16(v120[:], n, uint64(24), uint16(v92+2))
		bt_write16(v120[:], n, uint64(26), v128)
		v5 = v133
	}
	return uint8(1)
}

func bt_chain_split(heap []byte, npages uint64, src uint64, dst uint64) byte {
	var v7 uint64
	var v8 uint64
	var v9 uint64
	var v10 uint64
	var v11 uint64
	var v12 uint64
	var v14 uint64
	var v19 uint64
	var v49 uint64
	if src >= npages {
		return uint8(0)
	}
	if dst >= npages {
		return uint8(0)
	}
	if src == dst {
		return uint8(0)
	}
	v26 := src * 0x4000
	v30 := dst * 0x4000
	if Db_bt_leaf_init(heap[v30:], uint64(0x4000)).Ok == 0 {
		return uint8(0)
	}
	v43 := uint64(bt_read16(heap[v26:], uint64(0x4000), uint64(22)))
	v7 = v43 / 2
	if v7 == 0 {
		return uint8(0)
	}
	if v7 >= v43 {
		return uint8(0)
	}
	v49 = 0
	for v8 = v7; v8 < v43; v8++ {
		v9 = 64 + (v8 * 2)
		v10 = uint64(bt_read16(heap[v26:], 0x4000, v9))
		if (v10 >= 0x4000) || (v10 < 64) {
			return uint8(0)
		}
		v67 := heap[v26:]
		v11 = uint64(bt_read16(v67[:], 0x4000, v10))
		v12 = uint64(bt_read16(v67[:], 0x4000, (v10 + 2)))
		v49 += (((4 + v11) + v12) + 2)
	}
	for {
		v90 := (v7 < (v43 - 1)) && ((v49 + 0x9c4) > 0x3fc0)
		if !v90 {
			break
		}
		v9 = 64 + (v7 * 2)
		v95 := heap[v26:]
		v10 = uint64(bt_read16(v95[:], 0x4000, v9))
		v11 = uint64(bt_read16(v95[:], 0x4000, v10))
		v12 = uint64(bt_read16(v95[:], 0x4000, (v10 + 2)))
		v49 -= (((4 + v11) + v12) + 2)
		v7++
	}
	for v8 = v7; v8 < v43; v8++ {
		v9 = 64 + (v8 * 2)
		v121 := heap[v26:]
		v10 = uint64(bt_read16(v121[:], 0x4000, v9))
		if bt_bounds(v121[:], uint64(0x4000), v10, uint64(4)) == 0 {
			return uint8(0)
		}
		v131 := heap[v26:]
		v11 = uint64(bt_read16(v131[:], 0x4000, v10))
		v12 = uint64(bt_read16(v131[:], 0x4000, (v10 + 2)))
		v143 := (uint64(4) + v11) + v12
		if bt_bounds(v131[:], uint64(0x4000), v10, v143) == 0 {
			return uint8(0)
		}
		v149 := heap[v30:]
		v14 = uint64(bt_read16(v149[:], 0x4000, 22))
		v158 := uint64(bt_read16(v149[:], uint64(0x4000), uint64(24)))
		v163 := uint64(bt_read16(v149[:], uint64(0x4000), uint64(26)))
		if v158 >= 0x4000 {
			return uint8(0)
		}
		if 2 > (uint64(0x4000) - v158) {
			return uint8(0)
		}
		if v143 > v163 {
			return uint8(0)
		}
		v171 := v163 - v143
		if (v158 + 2) > v171 {
			return uint8(0)
		}
		if bt_bounds(heap[v30:], uint64(0x4000), v171, v143) == 0 {
			return uint8(0)
		}
		v180 := heap[v30:]
		bt_copy_bytes(v180[:], uint64(0x4000), v171, heap[v26:], uint64(0x4000), v10, v143)
		v188 := uint64(64) + (v14 * 2)
		if bt_bounds(v180[:], uint64(0x4000), v188, uint64(2)) == 0 {
			return uint8(0)
		}
		v195 := heap[v30:]
		v197 := uint16(v171)
		bt_write16(v195[:], uint64(0x4000), v188, v197)
		v14++
		bt_write16(v195[:], uint64(0x4000), uint64(22), uint16(v14))
		bt_write16(v195[:], uint64(0x4000), uint64(24), uint16(v158+2))
		bt_write16(v195[:], uint64(0x4000), uint64(26), v197)
	}
	v220 := heap[v26:]
	bt_write16(v220[:], uint64(0x4000), uint64(22), uint16(v7))
	bt_write16(v220[:], uint64(0x4000), uint64(24), uint16(uint64(64)+(v7*2)))
	v19 = 0x4000
	for v8 = 0; v8 < v7; v8++ {
		v9 = 64 + (v8 * 2)
		v10 = uint64(bt_read16(heap[v26:], 0x4000, v9))
		if v10 < v19 {
			v19 = v10
		}
	}
	v246 := heap[v26:]
	bt_write16(v246[:], uint64(0x4000), uint64(26), uint16(v19))
	bt_write64(heap[v30:], uint64(0x4000), uint64(8), bt_read64(v246[:], uint64(0x4000), uint64(8)))
	bt_write64(v246[:], uint64(0x4000), uint64(8), dst)
	if bt_leaf_repack(v246[:], uint64(0x4000), uint64(0)) == 0 {
		return uint8(0)
	}
	return uint8(1)
}

func bt_find_ver_pos(page []byte, n uint64, key []byte, klen uint64, id16 []byte) uint64 {
	var v6 uint64
	var v10 int32
	v13 := uint64(bt_read16(page[:], n, uint64(22)))
	for v6 = 0; v6 < v13; v6++ {
		v18 := uint64(64) + (v6 * 2)
		if bt_bounds(page[:], n, v18, uint64(2)) == 0 {
			return v6
		}
		v23 := uint64(bt_read16(page[:], n, v18))
		if bt_bounds(page[:], n, v23, uint64(4)) == 0 {
			return v6
		}
		v27 := bt_read16(page[:], n, v23)
		if bt_bounds(page[:], n, v23, ((uint64(4)+uint64(v27))+16)) == 0 {
			return v6
		}
		v10 = bt_keycmp_at(page[:], n, (v23 + 4), uint64(v27), key[:], klen)
		if v10 > 0 {
			return v6
		}
		if v10 == 0 {
			v10 = bt_keycmp_at(page[:], n, ((v23 + 4) + uint64(v27)), uint64(16), id16[:], uint64(16))
			if v10 > 0 {
				return v6
			}
		}
	}
	return v13
}

func bt_slot_insert(page []byte, n uint64, pos uint64, nslots uint64, cell_off uint16) {
	var v5 uint64
	var v6 uint64
	var v7 uint64
	var v9 uint64
	if uint64(len(page)) < n {
		n = uint64(len(page))
	}
	v5 = nslots
	for v5 > pos {
		v6 = 0
		for v7 = v6; v7 < v5; v7++ {
			v6 = v7
		}
		v9 = 64 + (v5 * 2)
		bt_write16(page[:], n, v9, bt_read16(page[:], n, (uint64(64)+(v6*2))))
		v5 = v6
	}
	v9 = 64 + (pos * 2)
	bt_write16(page[:], n, v9, cell_off)
}

func bt_internal_child(heap []byte, n uint64, base uint64, key []byte, klen uint64) uint64 {
	var v6 uint64
	var v9 uint64
	v9 = bt_read64(heap[:], n, (base + 8))
	for v6 = 0; v6 < uint64(bt_read16(heap[:], n, (base+22))); v6++ {
		v23 := uint64(64) + (v6 * 2)
		if bt_off_ok(n, base, v23, uint64(2)) == 0 {
			return v9
		}
		v29 := uint64(bt_read16(heap[:], n, (base + v23)))
		if bt_off_ok(n, base, v29, uint64(4)) == 0 {
			return v9
		}
		v34 := bt_read16(heap[:], n, (base + v29))
		if bt_off_ok(n, base, v29, ((uint64(4)+uint64(v34))+8)) == 0 {
			return v9
		}
		if bt_keycmp_at(heap[:], n, ((base+v29)+4), uint64(v34), key[:], klen) > 0 {
			return v9
		}
		v9 = bt_read64(heap[:], n, (((base + v29) + 4) + uint64(v34)))
	}
	return v9
}

func Db_bt_child_of(heap []byte, nbytes uint64, npages uint64, root uint64, key []byte, klen uint64) uint64 {
	if (heap == nil) || (npages == 0) {
		return npages
	}
	if (nbytes / 0x4000) != npages {
		return npages
	}
	if (npages * 0x4000) != nbytes {
		return npages
	}
	if root >= npages {
		return npages
	}
	if ((key == nil) || (klen == 0)) || (klen > 0xffff) {
		return npages
	}
	v26 := root * 0x4000
	if bt_read8(heap[:], nbytes, (v26+20)) == 2 {
		return uint64(bt_internal_child(heap[:], nbytes, v26, key[:], klen))
	}
	return root
}

func bt_make_internal(heap []byte, nbytes uint64, npages uint64, left uint64, right uint64, intern uint64) byte {
	var v8 uint64
	var v12 uint64
	var v13 uint64
	var v16 uint64
	if intern >= npages {
		return uint8(0)
	}
	if left >= npages {
		return uint8(0)
	}
	if right >= npages {
		return uint8(0)
	}
	if intern == left {
		return uint8(0)
	}
	if intern == right {
		return uint8(0)
	}
	v23 := intern * 0x4000
	if v23 >= nbytes {
		return uint8(0)
	}
	if 0x4000 > (nbytes - v23) {
		return uint8(0)
	}
	bt_write8(heap[:], nbytes, (v23 + 20), uint8(2))
	bt_write16(heap[:], nbytes, (v23 + 22), uint16(0))
	bt_write16(heap[:], nbytes, (v23 + 24), uint16(64))
	bt_write16(heap[:], nbytes, (v23 + 26), uint16(0x4000))
	bt_write64(heap[:], nbytes, (v23 + 8), left)
	v48 := right * 0x4000
	if v48 >= nbytes {
		return uint8(0)
	}
	if 0x4000 > (nbytes - v48) {
		return uint8(0)
	}
	v8 = 64
	if bt_off_ok(nbytes, v48, v8, uint64(2)) == 0 {
		return uint8(0)
	}
	v60 := uint64(bt_read16(heap[:], nbytes, (v48 + v8)))
	if bt_off_ok(nbytes, v48, v60, uint64(4)) == 0 {
		return uint8(0)
	}
	v67 := uint64(bt_read16(heap[:], nbytes, (v48 + v60)))
	if bt_off_ok(nbytes, v48, v60, (uint64(4)+v67)) == 0 {
		return uint8(0)
	}
	v76 := (uint64(4) + v67) + 8
	v12 = 64
	v13 = 0x4000
	if 2 > (uint64(0x4000) - v12) {
		return uint8(0)
	}
	v84 := v12 + 2
	if v76 > v13 {
		return uint8(0)
	}
	v86 := v13 - v76
	if v84 > v86 {
		return uint8(0)
	}
	if bt_off_ok(nbytes, v23, v86, v76) == 0 {
		return uint8(0)
	}
	v91 := v23 + v86
	bt_write16(heap[:], nbytes, v91, uint16(v67))
	bt_write16(heap[:], nbytes, (v91 + 2), uint16(0))
	v101 := v91 + 4
	bt_copy_bytes(heap[:], nbytes, v101, heap[:], nbytes, ((v48 + v60) + 4), v67)
	bt_write64(heap[:], nbytes, (v101 + v67), right)
	v16 = 64
	if bt_off_ok(nbytes, v23, v16, uint64(2)) == 0 {
		return uint8(0)
	}
	v117 := uint16(v86)
	bt_write16(heap[:], nbytes, (v23 + v16), v117)
	bt_write16(heap[:], nbytes, (v23 + 22), uint16(1))
	bt_write16(heap[:], nbytes, (v23 + 24), uint16(v84))
	bt_write16(heap[:], nbytes, (v23 + 26), v117)
	return uint8(1)
}

func bt_internal_insert_kv(heap []byte, nbytes uint64, npages uint64, intern uint64, left uint64, right uint64, koff uint64, cklen uint64) byte {
	var v14 uint64
	var v15 uint64
	var v16 uint64
	var v81 byte
	if intern >= npages {
		return uint8(0)
	}
	if right >= npages {
		return uint8(0)
	}
	if left >= npages {
		return uint8(0)
	}
	if intern == right {
		return uint8(0)
	}
	if (cklen == 0) || (cklen > 0xffff) {
		return uint8(0)
	}
	if koff >= nbytes {
		return uint8(0)
	}
	if cklen > (nbytes - koff) {
		return uint8(0)
	}
	v34 := intern * 0x4000
	if v34 >= nbytes {
		return uint8(0)
	}
	if 0x4000 > (nbytes - v34) {
		return uint8(0)
	}
	if bt_read8(heap[:], nbytes, (v34+20)) != 2 {
		return uint8(0)
	}
	v14 = uint64(bt_read16(heap[:], nbytes, (v34 + 22)))
	v51 := uint64(bt_read16(heap[:], nbytes, (v34 + 24)))
	v55 := uint64(bt_read16(heap[:], nbytes, (v34 + 26)))
	if v51 < 64 {
		return uint8(0)
	}
	if v55 > 0x4000 {
		return uint8(0)
	}
	if v51 > v55 {
		return uint8(0)
	}
	v64 := (uint64(4) + cklen) + 8
	if v51 >= 0x4000 {
		return uint8(0)
	}
	if 2 > (uint64(0x4000) - v51) {
		return uint8(0)
	}
	v72 := v51 + 2
	if v64 > v55 {
		return uint8(0)
	}
	v74 := v55 - v64
	if v72 > v74 {
		return uint8(0)
	}
	if bt_off_ok(nbytes, v34, v74, v64) == 0 {
		return uint8(0)
	}
	v15 = v14
	v81 = 0
	if bt_read64(heap[:], nbytes, (v34+8)) == left {
		v15 = 0
		v81 = 1
	} else {
		for v16 = 0; v16 < v14; v16++ {
			v92 := uint64(64) + (v16 * 2)
			if bt_off_ok(nbytes, v34, v92, uint64(2)) == 0 {
				return uint8(0)
			}
			v99 := uint64(bt_read16(heap[:], nbytes, (v34 + v92)))
			if bt_off_ok(nbytes, v34, v99, uint64(4)) == 0 {
				return uint8(0)
			}
			v105 := bt_read16(heap[:], nbytes, (v34 + v99))
			if bt_off_ok(nbytes, v34, v99, ((uint64(4)+uint64(v105))+8)) == 0 {
				return uint8(0)
			}
			if bt_read64(heap[:], nbytes, (((v34+v99)+4)+uint64(v105))) == left {
				v15 = v16 + 1
				v81 = 1
				break
			}
		}
	}
	if v81 == 0 {
		return uint8(0)
	}
	v127 := v34 + v74
	bt_write16(heap[:], nbytes, v127, uint16(cklen))
	bt_write16(heap[:], nbytes, (v127 + 2), uint16(0))
	v137 := v127 + 4
	bt_copy_bytes(heap[:], nbytes, v137, heap[:], nbytes, koff, cklen)
	bt_write64(heap[:], nbytes, (v137 + cklen), right)
	v149 := uint16(v74)
	bt_slot_insert(heap[int(intern*0x4000):], uint64(0x4000), v15, v14, v149)
	v14++
	bt_write16(heap[:], nbytes, (v34 + 22), uint16(v14))
	bt_write16(heap[:], nbytes, (v34 + 24), uint16(v72))
	bt_write16(heap[:], nbytes, (v34 + 26), v149)
	return uint8(1)
}

func bt_internal_insert_buf(heap []byte, nbytes uint64, npages uint64, intern uint64, left uint64, right uint64, key []byte, cklen uint64) byte {
	var v14 uint64
	var v15 uint64
	var v16 uint64
	var v84 byte
	if intern >= npages {
		return uint8(0)
	}
	if right >= npages {
		return uint8(0)
	}
	if left >= npages {
		return uint8(0)
	}
	if intern == right {
		return uint8(0)
	}
	if key == nil {
		return uint8(0)
	}
	if (cklen == 0) || (cklen > 0xffff) {
		return uint8(0)
	}
	if cklen > 0x4000 {
		return uint8(0)
	}
	v37 := intern * 0x4000
	if v37 >= nbytes {
		return uint8(0)
	}
	if 0x4000 > (nbytes - v37) {
		return uint8(0)
	}
	if bt_read8(heap[:], nbytes, (v37+20)) != 2 {
		return uint8(0)
	}
	v14 = uint64(bt_read16(heap[:], nbytes, (v37 + 22)))
	v54 := uint64(bt_read16(heap[:], nbytes, (v37 + 24)))
	v58 := uint64(bt_read16(heap[:], nbytes, (v37 + 26)))
	if v54 < 64 {
		return uint8(0)
	}
	if v58 > 0x4000 {
		return uint8(0)
	}
	if v54 > v58 {
		return uint8(0)
	}
	v67 := (uint64(4) + cklen) + 8
	if v54 >= 0x4000 {
		return uint8(0)
	}
	if 2 > (uint64(0x4000) - v54) {
		return uint8(0)
	}
	v75 := v54 + 2
	if v67 > v58 {
		return uint8(0)
	}
	v77 := v58 - v67
	if v75 > v77 {
		return uint8(0)
	}
	if bt_off_ok(nbytes, v37, v77, v67) == 0 {
		return uint8(0)
	}
	v15 = v14
	v84 = 0
	if bt_read64(heap[:], nbytes, (v37+8)) == left {
		v15 = 0
		v84 = 1
	} else {
		for v16 = 0; v16 < v14; v16++ {
			v95 := uint64(64) + (v16 * 2)
			if bt_off_ok(nbytes, v37, v95, uint64(2)) == 0 {
				return uint8(0)
			}
			v102 := uint64(bt_read16(heap[:], nbytes, (v37 + v95)))
			if bt_off_ok(nbytes, v37, v102, uint64(4)) == 0 {
				return uint8(0)
			}
			v108 := bt_read16(heap[:], nbytes, (v37 + v102))
			if bt_off_ok(nbytes, v37, v102, ((uint64(4)+uint64(v108))+8)) == 0 {
				return uint8(0)
			}
			if bt_read64(heap[:], nbytes, (((v37+v102)+4)+uint64(v108))) == left {
				v15 = v16 + 1
				v84 = 1
				break
			}
		}
	}
	if v84 == 0 {
		return uint8(0)
	}
	v130 := v37 + v77
	bt_write16(heap[:], nbytes, v130, uint16(cklen))
	bt_write16(heap[:], nbytes, (v130 + 2), uint16(0))
	v140 := v130 + 4
	bt_copy_in(heap[:], nbytes, v140, key[0:], cklen)
	bt_write64(heap[:], nbytes, (v140 + cklen), right)
	v153 := uint16(v77)
	bt_slot_insert(heap[int(intern*0x4000):], uint64(0x4000), v15, v14, v153)
	v14++
	bt_write16(heap[:], nbytes, (v37 + 22), uint16(v14))
	bt_write16(heap[:], nbytes, (v37 + 24), uint16(v75))
	bt_write16(heap[:], nbytes, (v37 + 26), v153)
	return uint8(1)
}

func bt_internal_add_sep(heap []byte, nbytes uint64, npages uint64, intern uint64, left uint64, right uint64) byte {
	var v7 uint64
	if right >= npages {
		return uint8(0)
	}
	v12 := right * 0x4000
	if v12 >= nbytes {
		return uint8(0)
	}
	if 0x4000 > (nbytes - v12) {
		return uint8(0)
	}
	v7 = 64
	if bt_off_ok(nbytes, v12, v7, uint64(2)) == 0 {
		return uint8(0)
	}
	v24 := uint64(bt_read16(heap[:], nbytes, (v12 + v7)))
	if bt_off_ok(nbytes, v12, v24, uint64(4)) == 0 {
		return uint8(0)
	}
	v31 := uint64(bt_read16(heap[:], nbytes, (v12 + v24)))
	if bt_off_ok(nbytes, v12, v24, (uint64(4)+v31)) == 0 {
		return uint8(0)
	}
	return byte(bt_internal_insert_kv(heap[:], nbytes, npages, intern, left, right, ((v12 + v24) + 4), v31))
}

func bt_internal_has_child(heap []byte, nbytes uint64, intern uint64, ch uint64, npages uint64) byte {
	var v7 uint64
	if (intern >= npages) || (ch >= npages) {
		return uint8(0)
	}
	v17 := intern * 0x4000
	if bt_read8(heap[:], nbytes, (v17+20)) != 2 {
		return uint8(0)
	}
	if bt_read64(heap[:], nbytes, (v17+8)) == ch {
		return uint8(1)
	}
	for v7 = 0; v7 < uint64(bt_read16(heap[:], nbytes, (v17+22))); v7++ {
		v35 := uint64(64) + (v7 * 2)
		if bt_off_ok(nbytes, v17, v35, uint64(2)) == 0 {
			return uint8(0)
		}
		v42 := uint64(bt_read16(heap[:], nbytes, (v17 + v35)))
		if bt_off_ok(nbytes, v17, v42, uint64(4)) == 0 {
			return uint8(0)
		}
		v48 := bt_read16(heap[:], nbytes, (v17 + v42))
		if bt_off_ok(nbytes, v17, v42, ((uint64(4)+uint64(v48))+8)) == 0 {
			return uint8(0)
		}
		if bt_read64(heap[:], nbytes, (((v17+v42)+4)+uint64(v48))) == ch {
			return uint8(1)
		}
	}
	return uint8(0)
}

func bt_elevate_root(heap []byte, nbytes uint64, npages uint64, src uint64, dst uint64, nroot uint64, left uint64, right uint64) byte {
	var v13 uint64
	var v14 uint64
	var v15 uint64
	var v17 uint64
	var v19 uint64
	var v20 uint64
	var v21 uint64
	var v24 uint64
	if ((src >= npages) || (dst >= npages)) || (nroot >= npages) {
		return uint8(0)
	}
	if ((src == dst) || (src == nroot)) || (dst == nroot) {
		return uint8(0)
	}
	v39 := src * 0x4000
	if bt_read8(heap[:], nbytes, (v39+20)) != 2 {
		return uint8(0)
	}
	v48 := uint64(bt_read16(heap[:], nbytes, (v39 + 22)))
	v50 := v48 / 2
	if v50 == 0 {
		return uint8(0)
	}
	if (v50 + 1) >= v48 {
		return uint8(0)
	}
	v14 = 64 + (v50 * 2)
	if bt_off_ok(nbytes, v39, v14, uint64(2)) == 0 {
		return uint8(0)
	}
	v15 = uint64(bt_read16(heap[:], nbytes, (v39 + v14)))
	if bt_off_ok(nbytes, v39, v15, uint64(4)) == 0 {
		return uint8(0)
	}
	v73 := uint64(bt_read16(heap[:], nbytes, (v39 + v15)))
	if bt_off_ok(nbytes, v39, v15, ((uint64(4)+v73)+8)) == 0 {
		return uint8(0)
	}
	v87 := dst * 0x4000
	bt_write8(heap[:], nbytes, (v87 + 20), uint8(2))
	bt_write16(heap[:], nbytes, (v87 + 22), uint16(0))
	bt_write16(heap[:], nbytes, (v87 + 24), uint16(64))
	bt_write16(heap[:], nbytes, (v87 + 26), uint16(0x4000))
	bt_write64(heap[:], nbytes, (v87 + 8), bt_read64(heap[:], nbytes, (((v39+v15)+4)+v73)))
	for v13 = v50 + 1; v13 < v48; v13++ {
		v14 = 64 + (v13 * 2)
		if bt_off_ok(nbytes, v39, v14, uint64(2)) == 0 {
			return uint8(0)
		}
		v15 = uint64(bt_read16(heap[:], nbytes, (v39 + v14)))
		if bt_off_ok(nbytes, v39, v15, uint64(4)) == 0 {
			return uint8(0)
		}
		v17 = (4 + uint64(bt_read16(heap[:], nbytes, (v39+v15)))) + 8
		if bt_off_ok(nbytes, v39, v15, v17) == 0 {
			return uint8(0)
		}
		v137 := uint64(bt_read16(heap[:], nbytes, (v87 + 22)))
		v19 = uint64(bt_read16(heap[:], nbytes, (v87 + 24)))
		v20 = uint64(bt_read16(heap[:], nbytes, (v87 + 26)))
		if 2 > (uint64(0x4000) - v19) {
			return uint8(0)
		}
		if v17 > v20 {
			return uint8(0)
		}
		v21 = v20 - v17
		if (v19 + 2) > v21 {
			return uint8(0)
		}
		bt_copy_bytes(heap[:], nbytes, (v87 + v21), heap[:], nbytes, (v39 + v15), v17)
		v163 := uint16(v21)
		bt_write16(heap[:], nbytes, (v87 + (uint64(64) + (v137 * 2))), v163)
		bt_write16(heap[:], nbytes, (v87 + 22), uint16(v137+1))
		bt_write16(heap[:], nbytes, (v87 + 24), uint16(v19+2))
		bt_write16(heap[:], nbytes, (v87 + 26), v163)
	}
	v184 := nroot * 0x4000
	bt_write8(heap[:], nbytes, (v184 + 20), uint8(2))
	bt_write16(heap[:], nbytes, (v184 + 22), uint16(0))
	bt_write16(heap[:], nbytes, (v184 + 24), uint16(64))
	bt_write16(heap[:], nbytes, (v184 + 26), uint16(0x4000))
	bt_write64(heap[:], nbytes, (v184 + 8), src)
	v17 = (4 + v73) + 8
	v19 = 64
	v20 = 0x4000
	v21 = v20 - v17
	if (v19 + 2) > v21 {
		return uint8(0)
	}
	v14 = 64 + (v50 * 2)
	v15 = uint64(bt_read16(heap[:], nbytes, (v39 + v14)))
	v221 := v184 + v21
	bt_write16(heap[:], nbytes, v221, uint16(v73))
	bt_write16(heap[:], nbytes, (v221 + 2), uint16(0))
	v231 := v221 + 4
	bt_copy_bytes(heap[:], nbytes, v231, heap[:], nbytes, ((v39 + v15) + 4), v73)
	bt_write64(heap[:], nbytes, (v231 + v73), dst)
	v243 := uint16(v21)
	bt_write16(heap[:], nbytes, (v184 + 64), v243)
	bt_write16(heap[:], nbytes, (v184 + 22), uint16(1))
	bt_write16(heap[:], nbytes, (v184 + 24), uint16(0x42))
	bt_write16(heap[:], nbytes, (v184 + 26), v243)
	bt_write16(heap[:], nbytes, (v39 + 22), uint16(v50))
	if bt_leaf_repack(heap[int(src*0x4000):], uint64(0x4000), uint64(8)) == 0 {
		return uint8(0)
	}
	v24 = src
	if bt_internal_has_child(heap[:], nbytes, dst, left, npages) != 0 {
		v24 = dst
	} else {
		if bt_internal_has_child(heap[:], nbytes, src, left, npages) == 0 {
			return uint8(0)
		}
	}
	return byte(bt_internal_add_sep(heap[:], nbytes, npages, v24, left, right))
}

func bt_split_internal(heap []byte, nbytes uint64, npages uint64, src uint64, dst uint64, keybuf []byte) uint64 {
	var v10 uint64
	var v11 uint64
	var v12 uint64
	if (src >= npages) || (dst >= npages) {
		return 0
	}
	if (src == dst) || (keybuf == nil) {
		return 0
	}
	v32 := src * 0x4000
	if bt_read8(heap[:], nbytes, (v32+20)) != 2 {
		return 0
	}
	v41 := uint64(bt_read16(heap[:], nbytes, (v32 + 22)))
	v43 := v41 / 2
	if v43 == 0 {
		return 0
	}
	if (v43 + 1) >= v41 {
		return 0
	}
	v11 = 64 + (v43 * 2)
	if bt_off_ok(nbytes, v32, v11, uint64(2)) == 0 {
		return 0
	}
	v12 = uint64(bt_read16(heap[:], nbytes, (v32 + v11)))
	if bt_off_ok(nbytes, v32, v12, uint64(4)) == 0 {
		return 0
	}
	v66 := uint64(bt_read16(heap[:], nbytes, (v32 + v12)))
	if ((v66 == 0) || (v66 > 0xffff)) || (v66 > 0x4000) {
		return 0
	}
	if bt_off_ok(nbytes, v32, v12, ((uint64(4)+v66)+8)) == 0 {
		return 0
	}
	v85 := (v32 + v12) + 4
	bt_copy_out(heap[:], nbytes, v85, keybuf[:], v66)
	v93 := dst * 0x4000
	bt_write8(heap[:], nbytes, (v93 + 20), uint8(2))
	bt_write16(heap[:], nbytes, (v93 + 22), uint16(0))
	bt_write16(heap[:], nbytes, (v93 + 24), uint16(64))
	bt_write16(heap[:], nbytes, (v93 + 26), uint16(0x4000))
	bt_write64(heap[:], nbytes, (v93 + 8), bt_read64(heap[:], nbytes, (v85+v66)))
	for v10 = v43 + 1; v10 < v41; v10++ {
		v11 = 64 + (v10 * 2)
		if bt_off_ok(nbytes, v32, v11, uint64(2)) == 0 {
			return 0
		}
		v12 = uint64(bt_read16(heap[:], nbytes, (v32 + v11)))
		if bt_off_ok(nbytes, v32, v12, uint64(4)) == 0 {
			return 0
		}
		v136 := (uint64(4) + uint64(bt_read16(heap[:], nbytes, (v32+v12)))) + 8
		if bt_off_ok(nbytes, v32, v12, v136) == 0 {
			return 0
		}
		v143 := uint64(bt_read16(heap[:], nbytes, (v93 + 22)))
		v147 := uint64(bt_read16(heap[:], nbytes, (v93 + 24)))
		v151 := uint64(bt_read16(heap[:], nbytes, (v93 + 26)))
		if 2 > (uint64(0x4000) - v147) {
			return 0
		}
		if v136 > v151 {
			return 0
		}
		v157 := v151 - v136
		if (v147 + 2) > v157 {
			return 0
		}
		bt_copy_bytes(heap[:], nbytes, (v93 + v157), heap[:], nbytes, (v32 + v12), v136)
		v169 := uint16(v157)
		bt_write16(heap[:], nbytes, (v93 + (uint64(64) + (v143 * 2))), v169)
		bt_write16(heap[:], nbytes, (v93 + 22), uint16(v143+1))
		bt_write16(heap[:], nbytes, (v93 + 24), uint16(v147+2))
		bt_write16(heap[:], nbytes, (v93 + 26), v169)
	}
	bt_write16(heap[:], nbytes, (v32 + 22), uint16(v43))
	if bt_leaf_repack(heap[int(src*0x4000):], uint64(0x4000), uint64(8)) == 0 {
		return 0
	}
	return v66
}

func bt_make_root_buf(heap []byte, nbytes uint64, npages uint64, left uint64, right uint64, nroot uint64, key []byte, cklen uint64) byte {
	var v10 uint64
	var v11 uint64
	if ((nroot >= npages) || (left >= npages)) || (right >= npages) {
		return uint8(0)
	}
	if (nroot == left) || (nroot == right) {
		return uint8(0)
	}
	if ((key == nil) || (cklen == 0)) || (cklen > 0xffff) {
		return uint8(0)
	}
	if cklen > 0x4000 {
		return uint8(0)
	}
	v36 := nroot * 0x4000
	if v36 >= nbytes {
		return uint8(0)
	}
	if 0x4000 > (nbytes - v36) {
		return uint8(0)
	}
	bt_write8(heap[:], nbytes, (v36 + 20), uint8(2))
	bt_write16(heap[:], nbytes, (v36 + 22), uint16(0))
	bt_write16(heap[:], nbytes, (v36 + 24), uint16(64))
	bt_write16(heap[:], nbytes, (v36 + 26), uint16(0x4000))
	bt_write64(heap[:], nbytes, (v36 + 8), left)
	v63 := (uint64(4) + cklen) + 8
	v10 = 64
	v11 = 0x4000
	if 2 > (uint64(0x4000) - v10) {
		return uint8(0)
	}
	v71 := v10 + 2
	if v63 > v11 {
		return uint8(0)
	}
	v73 := v11 - v63
	if v71 > v73 {
		return uint8(0)
	}
	if bt_off_ok(nbytes, v36, v73, v63) == 0 {
		return uint8(0)
	}
	v78 := v36 + v73
	bt_write16(heap[:], nbytes, v78, uint16(cklen))
	bt_write16(heap[:], nbytes, (v78 + 2), uint16(0))
	v88 := v78 + 4
	bt_copy_in(heap[:], nbytes, v88, key[:], cklen)
	bt_write64(heap[:], nbytes, (v88 + cklen), right)
	v97 := uint16(v73)
	bt_write16(heap[:], nbytes, (v36 + 64), v97)
	bt_write16(heap[:], nbytes, (v36 + 22), uint16(1))
	bt_write16(heap[:], nbytes, (v36 + 24), uint16(v71))
	bt_write16(heap[:], nbytes, (v36 + 26), v97)
	return uint8(1)
}

func bt_split_attach_deep(pub []byte, dirty []byte, nbytes uint64, npages uint64, anc []uint64, level uint64, root uint64, used uint64, mask uint64, src uint64, dst uint64, left uint64, right uint64) Db_bt_heap_st_t {
	var v16 uint64
	var v18 uint64
	var v19 uint64
	var v20 uint64
	var v22 uint64
	var v23 uint64
	var v24 uint64
	var v62 uint64
	var v13 Db_bt_heap_st_t
	var v14 [16384]byte
	var v15 [16384]byte
	v13.Root = 0
	v13.Used = 0
	v13.Nkeys = 0
	v13.Pages = 0
	v13.Ok = 0
	v13.Full = 0
	if ((anc == nil) || (level == 0)) || (level >= 32) {
		v13.Full = 1
		return v13
	}
	if (pub == nil) || (dirty == nil) {
		return v13
	}
	v16 = bt_split_internal(dirty[:], nbytes, npages, src, dst, v14[:])
	if v16 == 0 {
		return v13
	}
	v23 = src
	if bt_internal_has_child(dirty[:], nbytes, dst, left, npages) != 0 {
		v23 = dst
	} else {
		if bt_internal_has_child(dirty[:], nbytes, src, left, npages) == 0 {
			return v13
		}
	}
	if bt_internal_add_sep(dirty[:], nbytes, npages, v23, left, right) == 0 {
		return v13
	}
	v18 = src
	v19 = dst
	v20 = level
	for v20 > 0 {
		v56 := anc[int(v20-1)]
		if v56 >= npages {
			return v13
		}
		if bt_internal_insert_buf(dirty[:], nbytes, npages, v56, v18, v19, v14[:], v16) != 0 {
			v13.Root = root
			v13.Used = used
			v13.Nkeys = 0
			v13.Pages = mask
			v13.Ok = 1
			return v13
		}
		v62 = used + 1
		if (v62 > npages) || (v62 < used) {
			v13.Full = 1
			return v13
		}
		v22 = used
		mask = bt_cow_page(pub[:], dirty[:], nbytes, v22, mask)
		v70 := bt_split_internal(dirty[:], nbytes, npages, v56, v22, v15[:])
		if v70 == 0 {
			return v13
		}
		v23 = v56
		if bt_internal_has_child(dirty[:], nbytes, v22, v18, npages) != 0 {
			v23 = v22
		} else {
			if bt_internal_has_child(dirty[:], nbytes, v56, v18, npages) == 0 {
				return v13
			}
		}
		if bt_internal_insert_buf(dirty[:], nbytes, npages, v23, v18, v19, v14[:], v16) == 0 {
			return v13
		}
		used++
		v18 = v56
		v19 = v22
		bt_copy_bytes(v14[:], uint64(0x4000), uint64(0), v15[:], uint64(0x4000), uint64(0), v70)
		v16 = v70
		v20--
	}
	v88 := used + 1
	if (v88 > npages) || (v88 < used) {
		v13.Full = 1
		return v13
	}
	v24 = used
	mask = bt_cow_page(pub[:], dirty[:], nbytes, v24, mask)
	if bt_make_root_buf(dirty[:], nbytes, npages, v18, v19, v24, v14[:], v16) == 0 {
		return v13
	}
	v13.Root = v24
	v13.Used = used + 1
	v13.Nkeys = 0
	v13.Pages = mask
	v13.Ok = 1
	return v13
}

func bt_heap_nkeys(heap []byte, nbytes uint64, npages uint64, root uint64) uint64 {
	var v4 uint64
	var v5 uint64
	var v7 uint64
	var v8 uint64
	var v9 byte
	v7 = 0
	v4 = root
	if v4 >= npages {
		return v7
	}
	v8 = v4 * 0x4000
	v9 = bt_read8(heap[:], nbytes, (v8 + 20))
	if v9 == 2 {
		v4 = bt_read64(heap[:], nbytes, (v8 + 8))
	}
	for v5 = 0; v5 < npages; v5++ {
		if v4 >= npages {
			return v7
		}
		v8 = v4 * 0x4000
		v9 = bt_read8(heap[:], nbytes, (v8 + 20))
		if v9 == 1 {
			v7 += uint64(bt_read16(heap[:], nbytes, (v8 + 22)))
		}
		v34 := bt_read64(heap[:], nbytes, (v8 + 8))
		if v34 == 0 {
			return v7
		}
		if v34 == v4 {
			return v7
		}
		v4 = v34
	}
	return v7
}

func Db_bt_get_heap(heap []byte, nbytes uint64, npages uint64, root uint64, key []byte, klen uint64, out []byte, outn uint64) Db_bt_get_t {
	var v9 uint64
	var v10 uint64
	var v12 uint64
	var v14 byte
	var v8 Db_bt_get_t
	v8.Len_ = 0
	v8.Walked = 0
	v8.Found = 0
	v8.Fallback = 0
	if (heap == nil) || (npages == 0) {
		return v8
	}
	if (nbytes / 0x4000) != npages {
		return v8
	}
	if (npages * 0x4000) != nbytes {
		return v8
	}
	v9 = root
	v10 = 0
	if v9 >= npages {
		return v8
	}
	v12 = v9 * 0x4000
	v14 = bt_read8(heap[:], nbytes, (v12 + 20))
	for {
		v37 := (v14 == 2) && (v10 < npages)
		if !v37 {
			break
		}
		v38 := bt_internal_child(heap[:], nbytes, v12, key[:], klen)
		if v38 >= npages {
			v8.Walked = v10 + 1
			return v8
		}
		if v38 == v9 {
			v8.Walked = v10 + 1
			return v8
		}
		v9 = v38
		v10++
		v12 = v9 * 0x4000
		v14 = bt_read8(heap[:], nbytes, (v12 + 20))
	}
	if v14 == 2 {
		v8.Walked = v10
		return v8
	}
	if v10 != 0 {
		v8 = bt_get_at(heap[:], nbytes, v12, key[:], klen, out[:], outn)
		v8.Walked = v10 + 1
		v8.Fallback = 0
		return v8
	}
	for v10 < npages {
		if v9 >= npages {
			v8.Walked = v10
			return v8
		}
		v12 = v9 * 0x4000
		v8 = bt_get_at(heap[:], nbytes, v12, key[:], klen, out[:], outn)
		if v8.Found != 0 {
			v8.Walked = v10 + 1
			v8.Fallback = 0
			return v8
		}
		v66 := bt_read64(heap[:], nbytes, (v12 + 8))
		if v66 == 0 {
			v8.Walked = v10 + 1
			v8.Fallback = 0
			return v8
		}
		if v66 == v9 {
			v8.Walked = v10 + 1
			v8.Fallback = 0
			return v8
		}
		v9 = v66
		v10++
	}
	v8.Walked = v10
	v8.Fallback = 0
	return v8
}

func Db_bt_insert_heap(pub []byte, dirty []byte, nbytes uint64, npages uint64, st *Db_bt_heap_st_t, key []byte, klen uint64, val []byte, vlen uint64) Db_bt_heap_st_t {
	var v12 uint64
	var v13 uint64
	var v14 uint64
	var v15 uint64
	var v16 uint64
	var v17 uint64
	var v18 uint64
	var v19 uint64
	var v20 uint64
	var v21 uint64
	var v22 uint64
	var v24 byte
	var v25 int32
	var v27 uint64
	var v81 bool
	var v131 uint64
	var v167 uint64
	var v175 uint64
	v54 := uint64(0)
	var v9 Db_bt_heap_st_t
	var v10 Db_bt_state_t
	var v11 Db_bt_get_t
	var v26 [32]uint64
	var v28 Db_bt_heap_st_t
	v9.Root = 0
	v9.Used = 0
	v9.Nkeys = 0
	v9.Pages = 0
	v9.Ok = 0
	v9.Full = 0
	v21 = v54
	if (pub == nil) || (dirty == nil) {
		return v9
	}
	if npages == 0 {
		return v9
	}
	if (nbytes / 0x4000) != npages {
		return v9
	}
	if (npages * 0x4000) != nbytes {
		return v9
	}
	if ((klen == 0) || (klen > 0xffff)) || (vlen > 0xffff) {
		return v9
	}
	if key == nil {
		return v9
	}
	v61 := (vlen > 0) && (val == nil)
	if v61 {
		return v9
	}
	v15 = st.Used
	if v15 == 0 {
		v15 = 1
	}
	if st.Root >= npages {
		return v9
	}
	v12 = st.Root
	st.Root = v12
	v22 = st.Root
	v21 = bt_cow_page(pub[:], dirty[:], nbytes, v12, v21)
	v17 = v12 * 0x4000
	v24 = bt_read8(dirty[:], nbytes, (v17 + 20))
	if v24 == 2 {
		v26[0] = v12
		v27 = 1
		v13 = 0
		for {
			v81 = (v24 == 2) && (v13 < npages)
			if !v81 {
				break
			}
			v22 = v12
			v83 := bt_internal_child(dirty[:], nbytes, v17, key[v54:], klen)
			if v83 >= npages {
				return v9
			}
			if v83 == v12 {
				return v9
			}
			v12 = v83
			v21 = bt_cow_page(pub[:], dirty[:], nbytes, v12, v21)
			v17 = v12 * 0x4000
			v24 = bt_read8(dirty[:], nbytes, (v17 + 20))
			v13++
			if v24 == 2 {
				if v27 >= 32 {
					return v9
				}
				v26[v27] = v12
				v27++
			}
		}
		if v24 == 2 {
			return v9
		}
		v11 = bt_get_at(dirty[:], nbytes, v17, key[v54:], klen, nil, uint64(0))
		if v11.Found != 0 {
			v10 = bt_insert_at(dirty[:], nbytes, v17, key[v54:], klen, val[:], vlen)
			if v10.Ok == 0 {
				return v9
			}
			v9.Root = st.Root
			v9.Used = v15
			v9.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
			v9.Pages = v21
			v9.Ok = 1
			return v9
		}
		v10 = bt_insert_at(dirty[:], nbytes, v17, key[v54:], klen, val[:], vlen)
		if v10.Ok != 0 {
			v9.Root = st.Root
			v9.Used = v15
			v9.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
			v9.Pages = v21
			v9.Ok = 1
			return v9
		}
		if v15 >= npages {
			return v9
		}
		v21 = bt_cow_page(pub[:], dirty[:], nbytes, v15, v21)
		if bt_chain_split(dirty[:], npages, v12, v15) == 0 {
			return v9
		}
		v17 = v15 * 0x4000
		v19 = uint64(bt_read16(dirty[:], nbytes, (v17 + 64)))
		if bt_off_ok(nbytes, v17, v19, uint64(4)) == 0 {
			return v9
		}
		v131 = v17 + v19
		v20 = uint64(bt_read16(dirty[:], nbytes, v131))
		v25 = bt_keycmp_at(dirty[:], nbytes, (v131 + 4), v20, key[v54:], klen)
		if v25 > 0 {
			v17 = v12 * 0x4000
			v10 = bt_insert_at(dirty[:], nbytes, v17, key[v54:], klen, val[:], vlen)
		} else {
			v21 = bt_cow_page(pub[:], dirty[:], nbytes, v15, v21)
			v17 = v15 * 0x4000
			v10 = bt_insert_at(dirty[:], nbytes, v17, key[v54:], klen, val[:], vlen)
		}
		if v10.Ok == 0 {
			return v9
		}
		if bt_internal_add_sep(dirty[:], nbytes, npages, v22, v12, v15) != 0 {
			v9.Root = st.Root
			v9.Used = v15 + 1
			v9.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
			v9.Pages = v21
			v9.Ok = 1
			return v9
		}
		v18 = v15 + 1
		if v22 == st.Root {
			if (v18 + 1) >= npages {
				v9.Full = 1
				return v9
			}
			v21 = bt_cow_page(pub[:], dirty[:], nbytes, v18, v21)
			v167 = v18 + 1
			v21 = bt_cow_page(pub[:], dirty[:], nbytes, v167, v21)
			if bt_elevate_root(dirty[:], nbytes, npages, st.Root, v18, v167, v12, v15) == 0 {
				return v9
			}
			v175 = v18 + 1
			v9.Root = v175
			v9.Used = v15 + 3
			v9.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, v175)
			v9.Pages = v21
			v9.Ok = 1
			return v9
		}
		if v18 >= npages {
			v9.Full = 1
			return v9
		}
		v21 = bt_cow_page(pub[:], dirty[:], nbytes, v18, v21)
		v28 = bt_split_attach_deep(pub[:], dirty[:], nbytes, npages, v26[:], (v27 - 1), st.Root, (v15 + 2), v21, v22, v18, v12, v15)
		if v28.Ok == 0 {
			v9.Full = v28.Full
			return v9
		}
		v9.Root = v28.Root
		v9.Used = v28.Used
		v9.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, v28.Root)
		v9.Pages = v28.Pages
		v9.Ok = 1
		return v9
	}
	v12 = st.Root
	v13 = 0
	v16 = v12
	for v13 < npages {
		if v12 >= npages {
			return v9
		}
		v21 = bt_cow_page(pub[:], dirty[:], nbytes, v12, v21)
		v17 = v12 * 0x4000
		v11 = bt_get_at(dirty[:], nbytes, v17, key[v54:], klen, nil, uint64(0))
		if v11.Found != 0 {
			v10 = bt_insert_at(dirty[:], nbytes, v17, key[v54:], klen, val[:], vlen)
			if v10.Ok == 0 {
				return v9
			}
			v9.Root = st.Root
			v9.Used = v15
			v9.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
			v9.Pages = v21
			v9.Ok = 1
			return v9
		}
		v16 = v12
		v14 = bt_read64(dirty[:], nbytes, (v17 + 8))
		if v14 == 0 {
			break
		}
		if v14 == v12 {
			break
		}
		v12 = v14
		v13++
	}
	v12 = st.Root
	for v13 = 0; v13 < npages; v13++ {
		if v12 >= npages {
			break
		}
		v21 = bt_cow_page(pub[:], dirty[:], nbytes, v12, v21)
		v17 = v12 * 0x4000
		v10 = bt_insert_at(dirty[:], nbytes, v17, key[v54:], klen, val[:], vlen)
		if v10.Ok != 0 {
			v9.Root = st.Root
			v9.Used = v15
			v9.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
			v9.Pages = v21
			v9.Ok = 1
			return v9
		}
		v16 = v12
		v14 = bt_read64(dirty[:], nbytes, (v17 + 8))
		if v14 == 0 {
			break
		}
		if v14 == v12 {
			break
		}
		v12 = v14
	}
	if v16 != st.Root {
		return v9
	}
	if v15 >= npages {
		return v9
	}
	v247 := v15 + 2
	v253 := (npages > 2) && ((v247 > npages) || (v247 < v15))
	if v253 {
		return v9
	}
	v21 = bt_cow_page(pub[:], dirty[:], nbytes, v15, v21)
	if bt_chain_split(dirty[:], npages, v16, v15) == 0 {
		return v9
	}
	v17 = v15 * 0x4000
	v19 = uint64(bt_read16(dirty[:], nbytes, (v17 + 64)))
	if bt_off_ok(nbytes, v17, v19, uint64(4)) == 0 {
		return v9
	}
	v266 := v17 + v19
	v20 = uint64(bt_read16(dirty[:], nbytes, v266))
	v25 = bt_keycmp_at(dirty[:], nbytes, (v266 + 4), v20, key[v54:], klen)
	if v25 > 0 {
		v17 = v16 * 0x4000
		v10 = bt_insert_at(dirty[:], nbytes, v17, key[v54:], klen, val[:], vlen)
	} else {
		v17 = v15 * 0x4000
		v10 = bt_insert_at(dirty[:], nbytes, v17, key[v54:], klen, val[:], vlen)
	}
	if v10.Ok == 0 {
		return v9
	}
	v18 = v15 + 1
	if v18 < npages {
		v21 = bt_cow_page(pub[:], dirty[:], nbytes, v18, v21)
		if bt_make_internal(dirty[:], nbytes, npages, st.Root, v15, v18) == 0 {
			return v9
		}
		v9.Root = v18
		v9.Used = v15 + 2
		v9.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, v18)
		v9.Pages = v21
		v9.Ok = 1
		return v9
	}
	if npages == 2 {
		v9.Root = st.Root
		v9.Used = v15 + 1
		v9.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
		v9.Pages = v21
		v9.Ok = 1
		return v9
	}
	return v9
}

func Db_bt_insert_ver(pub []byte, dirty []byte, n uint64, key []byte, klen uint64, id16 []byte, val []byte, vlen uint64) Db_bt_state_t {
	var v9 uint64
	var v16 uint64
	var v8 Db_bt_state_t
	v8.Nkeys = 0
	v8.Ok = 0
	v8.Copied = 0
	if ((pub == nil) || (dirty == nil)) || (n != 0x4000) {
		return v8
	}
	bt_cow(pub[:], dirty[:], n)
	v8.Copied = 1
	if ((klen == 0) || (klen > 0xffff)) || (vlen > 0xffff) {
		return v8
	}
	if (key == nil) || (id16 == nil) {
		return v8
	}
	v48 := (vlen > 0) && (val == nil)
	if v48 {
		return v8
	}
	if bt_read8(dirty[:], n, uint64(20)) != 1 {
		return v8
	}
	v9 = uint64(bt_read16(dirty[:], n, 22))
	v57 := uint64(bt_read16(dirty[:], n, uint64(24)))
	v60 := uint64(bt_read16(dirty[:], n, uint64(26)))
	v8.Nkeys = v9
	if v57 < 64 {
		return v8
	}
	if v60 > n {
		return v8
	}
	if v57 > v60 {
		return v8
	}
	v66 := ((uint64(4) + klen) + 16) + vlen
	if v57 >= n {
		return v8
	}
	if 2 > (n - v57) {
		return v8
	}
	v70 := v57 + 2
	if v66 > v60 {
		return v8
	}
	v71 := v60 - v66
	if v70 > v71 {
		return v8
	}
	if bt_bounds(dirty[:], n, v71, v66) == 0 {
		return v8
	}
	v16 = bt_find_ver_pos(dirty[:], n, key[:], klen, id16[:])
	if v16 > v9 {
		v16 = v9
	}
	bt_write16(dirty[:], n, v71, uint16(klen))
	bt_write16(dirty[:], n, (v71 + 2), uint16(vlen))
	v82 := v71 + 4
	bt_copy_in(dirty[:], n, v82, key[:], klen)
	bt_copy_in(dirty[:], n, (v82 + klen), id16[:], uint64(16))
	if vlen > 0 {
		bt_copy_in(dirty[:], n, (((v71 + 4) + klen) + 16), val[:], vlen)
	}
	v96 := uint16(v71)
	bt_slot_insert(dirty[:], n, v16, v9, v96)
	v9++
	bt_write16(dirty[:], n, uint64(22), uint16(v9))
	bt_write16(dirty[:], n, uint64(24), uint16(v70))
	bt_write16(dirty[:], n, uint64(26), v96)
	v8.Nkeys = v9
	v8.Ok = 1
	return v8
}

func Db_bt_get_as_of(page []byte, n uint64, key []byte, klen uint64, snap16 []byte, out []byte, outn uint64) Db_bt_get_t {
	var v9 uint64
	var v12 uint64
	var v13 uint64
	var v14 uint64
	var v15 uint16
	var v16 uint16
	var v18 byte
	var v20 int32
	v28 := uint64(0)
	var v7 Db_bt_get_t
	v7.Len_ = 0
	v7.Walked = 0
	v7.Found = 0
	v7.Fallback = 0
	v12 = v28
	v13 = v12
	v18 = 0
	if (page == nil) || (n != 0x4000) {
		return v7
	}
	if (((key == nil) || (snap16 == nil)) || (klen == 0)) || (klen > 0xffff) {
		return v7
	}
	if bt_read8(page[v28:], n, uint64(20)) != 1 {
		return v7
	}
	for v9 = 0; v9 < uint64(bt_read16(page[v28:], n, uint64(22))); v9++ {
		v58 := uint64(64) + (v9 * 2)
		if bt_bounds(page[v28:], n, v58, uint64(2)) == 0 {
			return v7
		}
		v63 := page[v28:]
		v65 := uint64(bt_read16(v63[:], n, v58))
		if bt_bounds(v63[:], n, v65, uint64(4)) == 0 {
			return v7
		}
		v70 := page[v28:]
		v15 = bt_read16(v70[:], n, v65)
		v16 = bt_read16(v70[:], n, (v65 + 2))
		if bt_bounds(v70[:], n, v65, (((uint64(4)+uint64(v15))+16)+uint64(v16))) == 0 {
			return v7
		}
		if bt_keycmp_at(page[v28:], n, (v65+4), uint64(v15), key[:], klen) == 0 {
			v20 = bt_keycmp_at(page[v28:], n, ((v65 + 4) + uint64(v15)), uint64(16), snap16[:], uint64(16))
			if v20 <= 0 {
				if v18 == 0 {
					v12 = v65
					v13 = (v65 + 4) + uint64(v15)
					v18 = 1
				} else {
					v20 = bt_keycmp_pp(page[v28:], n, ((v65 + 4) + uint64(v15)), uint64(16), v13, uint64(16))
					if v20 > 0 {
						v12 = v65
						v13 = (v65 + 4) + uint64(v15)
					}
				}
			}
		}
	}
	if v18 == 0 {
		return v7
	}
	v123 := page[v28:]
	v15 = bt_read16(v123[:], n, v12)
	v16 = bt_read16(v123[:], n, (v12 + 2))
	v129 := uint64(v16)
	v7.Len_ = v129
	v7.Found = 1
	v14 = v129
	if v14 > outn {
		v14 = outn
	}
	v138 := (out != nil) && (v14 > 0)
	if v138 {
		bt_copy_out(page[v28:], n, (((v12 + 4) + uint64(v15)) + 16), out[v28:], v14)
	}
	return v7
}

func Db_bt_gc_before(pub []byte, dirty []byte, n uint64, min_id16 []byte) Db_bt_state_t {
	var v6 uint64
	var v7 uint64
	var v4 Db_bt_state_t
	v4.Nkeys = 0
	v4.Ok = 0
	v4.Copied = 0
	if ((pub == nil) || (dirty == nil)) || (n != 0x4000) {
		return v4
	}
	if min_id16 == nil {
		return v4
	}
	bt_cow(pub[:], dirty[:], n)
	v4.Copied = 1
	if bt_read8(dirty[:], n, uint64(20)) != 1 {
		return v4
	}
	v7 = 0
	for v6 = v7; v6 < uint64(bt_read16(dirty[:], n, uint64(22))); v6++ {
		v41 := uint64(64) + (v6 * 2)
		if bt_bounds(dirty[:], n, v41, uint64(2)) == 0 {
			return v4
		}
		v45 := bt_read16(dirty[:], n, v41)
		v46 := uint64(v45)
		if bt_bounds(dirty[:], n, v46, uint64(4)) == 0 {
			return v4
		}
		v50 := bt_read16(dirty[:], n, v46)
		if bt_bounds(dirty[:], n, v46, ((uint64(4)+uint64(v50))+16)) == 0 {
			return v4
		}
		if bt_keycmp_at(dirty[:], n, ((v46+4)+uint64(v50)), uint64(16), min_id16[0:], uint64(16)) >= 0 {
			if v7 != v6 {
				bt_write16(dirty[:], n, (uint64(64) + (v7 * 2)), v45)
			}
			v7++
		}
	}
	bt_write16(dirty[:], n, uint64(22), uint16(v7))
	bt_write16(dirty[:], n, uint64(24), uint16(uint64(64)+(v7*2)))
	v4.Nkeys = v7
	v4.Ok = 1
	return v4
}

func bt_keyhas_prefix(page []byte, n uint64, koff uint64, klen uint64, prefix []byte, plen uint64) byte {
	var v6 uint64
	var v23 bool
	if plen == 0 {
		return uint8(1)
	}
	if (page == nil) || (prefix == nil) {
		return uint8(0)
	}
	if klen < plen {
		return uint8(0)
	}
	for v6 = 0; v6 < plen; v6++ {
		v18 := koff + v6
		v23 = (v18 < n) && (1 <= (n - v18))
		if v23 {
			if page[v18] != prefix[v6] {
				return uint8(0)
			}
		} else {
			return uint8(0)
		}
	}
	return uint8(1)
}

func bt_scan_prefix_at(heap []byte, n uint64, base uint64, prefix []byte, plen uint64, out []byte, outn uint64, already uint64) Db_bt_scan_t {
	var v10 uint64
	var v81 uint64
	var v84 uint64
	v21 := uint64(0)
	var v8 Db_bt_scan_t
	v8.Nfound = 0
	v8.Ok = 0
	if heap == nil {
		return v8
	}
	v28 := (plen > 0) && (prefix == nil)
	if v28 {
		return v8
	}
	if bt_read8(heap[v21:], n, (base+20)) != 1 {
		return v8
	}
	for v10 = 0; v10 < uint64(bt_read16(heap[v21:], n, (base+22))); v10++ {
		v43 := uint64(64) + (v10 * 2)
		if bt_off_ok(n, base, v43, uint64(2)) == 0 {
			return v8
		}
		v50 := uint64(bt_read16(heap[v21:], n, (base + v43)))
		if bt_off_ok(n, base, v50, uint64(4)) == 0 {
			return v8
		}
		v57 := uint64(bt_read16(heap[v21:], n, (base + v50)))
		if v57 > 0x4000 {
			return v8
		}
		if 4 > (uint64(0x4000) - v57) {
			return v8
		}
		if bt_off_ok(n, base, v50, (uint64(4)+v57)) == 0 {
			return v8
		}
		if v50 >= 0x4000 {
			return v8
		}
		if 4 > (uint64(0x4000) - v50) {
			return v8
		}
		v71 := v50 + 4
		if base >= n {
			return v8
		}
		if v71 > (n - base) {
			return v8
		}
		if bt_keyhas_prefix(heap[v21:], n, (base+v71), v57, prefix[:], plen) != 0 {
			if already > (uint64(0x7fffffffffffffff) - v8.Nfound) {
				return v8
			}
			v81 = already + v8.Nfound
			if v81 > 0x7fffffffffffffff {
				return v8
			}
			v84 = v81 * 4
			if (v84 >= outn) || (4 > (outn - v84)) {
				return v8
			}
			if out != nil {
				bt_write32(out[v21:], outn, v84, uint32(base+v50))
			}
			v8.Nfound += 1
		}
	}
	v8.Ok = 1
	return v8
}

func Db_bt_scan_prefix(page []byte, n uint64, prefix []byte, plen uint64, out []byte, outn uint64) Db_bt_scan_t {
	var v6 Db_bt_scan_t
	v6.Nfound = 0
	v6.Ok = 0
	if (page == nil) || (n != 0x4000) {
		return v6
	}
	return bt_scan_prefix_at(page[0:], n, uint64(0), prefix[:], plen, out[:], outn, uint64(0))
}

func Db_bt_scan_prefix_heap(heap []byte, nbytes uint64, npages uint64, root uint64, prefix []byte, plen uint64, out []byte, outn uint64) Db_bt_scan_t {
	var v10 uint64
	var v11 uint64
	var v12 uint64
	var v13 uint64
	var v14 byte
	var v8 Db_bt_scan_t
	var v9 Db_bt_scan_t
	v8.Nfound = 0
	v8.Ok = 0
	if (heap == nil) || (npages == 0) {
		return v8
	}
	if (nbytes / 0x4000) != npages {
		return v8
	}
	if (npages * 0x4000) != nbytes {
		return v8
	}
	v10 = root
	if v10 >= npages {
		return v8
	}
	v13 = v10 * 0x4000
	v14 = bt_read8(heap[:], nbytes, (v13 + 20))
	if v14 == 2 {
		v10 = bt_read64(heap[:], nbytes, (v13 + 8))
	}
	for v11 = 0; v11 < npages; v11++ {
		if v10 >= npages {
			return v8
		}
		v13 = v10 * 0x4000
		v14 = bt_read8(heap[:], nbytes, (v13 + 20))
		if v14 == 1 {
			v9 = bt_scan_prefix_at(heap[:], nbytes, v13, prefix[:], plen, out[:], outn, v8.Nfound)
			if v9.Ok == 0 {
				return v8
			}
			v8.Nfound += v9.Nfound
			v12 = bt_read64(heap[:], nbytes, (v13 + 8))
			if ((v12 == 0) || (v12 == v10)) || (v12 >= npages) {
				v8.Ok = 1
				return v8
			}
		} else {
			if v14 == 2 {
				v12 = bt_read64(heap[:], nbytes, (v13 + 8))
				if (v12 >= npages) || (v12 == v10) {
					return v8
				}
			} else {
				return v8
			}
		}
		v10 = v12
	}
	v8.Ok = 1
	return v8
}

func bt_chain_split_ver(heap []byte, npages uint64, src uint64, dst uint64) byte {
	var v7 uint64
	var v8 uint64
	var v9 uint64
	var v10 uint64
	var v11 uint64
	var v12 uint64
	var v14 uint64
	var v19 uint64
	var v49 uint64
	if src >= npages {
		return uint8(0)
	}
	if dst >= npages {
		return uint8(0)
	}
	if src == dst {
		return uint8(0)
	}
	v26 := src * 0x4000
	v30 := dst * 0x4000
	if Db_bt_leaf_init(heap[v30:], uint64(0x4000)).Ok == 0 {
		return uint8(0)
	}
	v43 := uint64(bt_read16(heap[v26:], uint64(0x4000), uint64(22)))
	v7 = v43 / 2
	if v7 == 0 {
		return uint8(0)
	}
	if v7 >= v43 {
		return uint8(0)
	}
	v49 = 0
	for v8 = v7; v8 < v43; v8++ {
		v9 = 64 + (v8 * 2)
		v10 = uint64(bt_read16(heap[v26:], 0x4000, v9))
		if (v10 >= 0x4000) || (v10 < 64) {
			return uint8(0)
		}
		v67 := heap[v26:]
		v11 = uint64(bt_read16(v67[:], 0x4000, v10))
		v12 = uint64(bt_read16(v67[:], 0x4000, (v10 + 2)))
		v49 += ((((4 + v11) + 16) + v12) + 2)
	}
	for {
		v92 := (v7 < (v43 - 1)) && ((v49 + 0x9c4) > 0x3fc0)
		if !v92 {
			break
		}
		v9 = 64 + (v7 * 2)
		v97 := heap[v26:]
		v10 = uint64(bt_read16(v97[:], 0x4000, v9))
		v11 = uint64(bt_read16(v97[:], 0x4000, v10))
		v12 = uint64(bt_read16(v97[:], 0x4000, (v10 + 2)))
		v49 -= ((((4 + v11) + 16) + v12) + 2)
		v7++
	}
	v121 := v7
	for v7 < v43 {
		v135 := heap[v26:]
		v138 := uint64(bt_read16(v135[:], uint64(0x4000), (uint64(64) + ((v7 - 1) * 2))))
		v143 := uint64(bt_read16(v135[:], uint64(0x4000), (uint64(64) + (v7 * 2))))
		v148 := uint64(bt_read16(v135[:], uint64(0x4000), v138))
		v153 := uint64(bt_read16(v135[:], uint64(0x4000), v143))
		if (v148 != v153) || (bt_keycmp_at(v135[:], uint64(0x4000), (v138+4), v148, heap[int((v26+v143)+4):], v153) != 0) {
			break
		}
		v7++
	}
	if v7 >= v43 {
		v7 = v121
		for v7 > 1 {
			v180 := heap[v26:]
			v183 := uint64(bt_read16(v180[:], uint64(0x4000), (uint64(64) + ((v7 - 1) * 2))))
			v188 := uint64(bt_read16(v180[:], uint64(0x4000), v183))
			v203 := (((uint64(4) + v188) + 16) + uint64(bt_read16(v180[:], uint64(0x4000), (v183+2)))) + 2
			if ((v49 + v203) + 0x9c4) > 0x3fc0 {
				return uint8(0)
			}
			v49 += v203
			v216 := heap[v26:]
			v219 := uint64(bt_read16(v216[:], uint64(0x4000), (uint64(64) + (v7 * 2))))
			v224 := uint64(bt_read16(v216[:], uint64(0x4000), v219))
			if (v188 != v224) || (bt_keycmp_at(v216[:], uint64(0x4000), (v183+4), v188, heap[int((v26+v219)+4):], v224) != 0) {
				break
			}
			v7--
		}
	}
	if (v7 <= 1) || (v7 >= v43) {
		return uint8(0)
	}
	for v8 = v7; v8 < v43; v8++ {
		v9 = 64 + (v8 * 2)
		v251 := heap[v26:]
		v10 = uint64(bt_read16(v251[:], 0x4000, v9))
		if bt_bounds(v251[:], uint64(0x4000), v10, uint64(4)) == 0 {
			return uint8(0)
		}
		v261 := heap[v26:]
		v11 = uint64(bt_read16(v261[:], 0x4000, v10))
		v12 = uint64(bt_read16(v261[:], 0x4000, (v10 + 2)))
		v275 := ((uint64(4) + v11) + 16) + v12
		if bt_bounds(v261[:], uint64(0x4000), v10, v275) == 0 {
			return uint8(0)
		}
		v281 := heap[v30:]
		v14 = uint64(bt_read16(v281[:], 0x4000, 22))
		v290 := uint64(bt_read16(v281[:], uint64(0x4000), uint64(24)))
		v295 := uint64(bt_read16(v281[:], uint64(0x4000), uint64(26)))
		if v290 >= 0x4000 {
			return uint8(0)
		}
		if 2 > (uint64(0x4000) - v290) {
			return uint8(0)
		}
		if v275 > v295 {
			return uint8(0)
		}
		v303 := v295 - v275
		if (v290 + 2) > v303 {
			return uint8(0)
		}
		if bt_bounds(heap[v30:], uint64(0x4000), v303, v275) == 0 {
			return uint8(0)
		}
		v312 := heap[v30:]
		bt_copy_bytes(v312[:], uint64(0x4000), v303, heap[v26:], uint64(0x4000), v10, v275)
		v320 := uint64(64) + (v14 * 2)
		if bt_bounds(v312[:], uint64(0x4000), v320, uint64(2)) == 0 {
			return uint8(0)
		}
		v327 := heap[v30:]
		v329 := uint16(v303)
		bt_write16(v327[:], uint64(0x4000), v320, v329)
		v14++
		bt_write16(v327[:], uint64(0x4000), uint64(22), uint16(v14))
		bt_write16(v327[:], uint64(0x4000), uint64(24), uint16(v290+2))
		bt_write16(v327[:], uint64(0x4000), uint64(26), v329)
	}
	v352 := heap[v26:]
	bt_write16(v352[:], uint64(0x4000), uint64(22), uint16(v7))
	bt_write16(v352[:], uint64(0x4000), uint64(24), uint16(uint64(64)+(v7*2)))
	v19 = 0x4000
	for v8 = 0; v8 < v7; v8++ {
		v9 = 64 + (v8 * 2)
		v10 = uint64(bt_read16(heap[v26:], 0x4000, v9))
		if v10 < v19 {
			v19 = v10
		}
	}
	v378 := heap[v26:]
	bt_write16(v378[:], uint64(0x4000), uint64(26), uint16(v19))
	bt_write64(heap[v30:], uint64(0x4000), uint64(8), bt_read64(v378[:], uint64(0x4000), uint64(8)))
	bt_write64(v378[:], uint64(0x4000), uint64(8), dst)
	if bt_leaf_repack(v378[:], uint64(0x4000), uint64(16)) == 0 {
		return uint8(0)
	}
	return uint8(1)
}

func bt_find_ver_pos_at(heap []byte, n uint64, base uint64, key []byte, klen uint64, id16 []byte) uint64 {
	var v7 uint64
	var v11 int32
	v15 := uint64(bt_read16(heap[:], n, (base + 22)))
	for v7 = 0; v7 < v15; v7++ {
		v20 := uint64(64) + (v7 * 2)
		if bt_off_ok(n, base, v20, uint64(2)) == 0 {
			return v7
		}
		v26 := uint64(bt_read16(heap[:], n, (base + v20)))
		if bt_off_ok(n, base, v26, uint64(4)) == 0 {
			return v7
		}
		v31 := bt_read16(heap[:], n, (base + v26))
		if bt_off_ok(n, base, v26, ((uint64(4)+uint64(v31))+16)) == 0 {
			return v7
		}
		v11 = bt_keycmp_at(heap[:], n, ((base + v26) + 4), uint64(v31), key[:], klen)
		if v11 > 0 {
			return v7
		}
		if v11 == 0 {
			v11 = bt_keycmp_at(heap[:], n, (((base + v26) + 4) + uint64(v31)), uint64(16), id16[:], uint64(16))
			if v11 > 0 {
				return v7
			}
		}
	}
	return v15
}

func bt_slot_insert_at(heap []byte, n uint64, base uint64, pos uint64, nslots uint64, cell_off uint16) {
	var v6 uint64
	var v7 uint64
	var v8 uint64
	var v10 uint64
	if uint64(len(heap)) < n {
		n = uint64(len(heap))
	}
	v6 = nslots
	for v6 > pos {
		v7 = 0
		for v8 = v7; v8 < v6; v8++ {
			v7 = v8
		}
		v10 = 64 + (v6 * 2)
		bt_write16(heap[:], n, (base + v10), bt_read16(heap[:], n, (base+(uint64(64)+(v7*2)))))
		v6 = v7
	}
	v10 = 64 + (pos * 2)
	bt_write16(heap[:], n, (base + v10), cell_off)
}

func bt_replace_same_value_at(heap []byte, n uint64, base uint64, key []byte, klen uint64, id16 []byte, val []byte, vlen uint64) byte {
	var v9 uint64
	var v12 uint64
	var v14 uint16
	var v15 uint16
	var v17 byte
	var v102 bool
	var v109 uint64
	v21 := uint64(0)
	v12 = v21
	v17 = 0
	if heap == nil {
		return uint8(0)
	}
	if (((key == nil) || (klen == 0)) || (klen > 0xffff)) || (vlen > 0xffff) {
		return uint8(0)
	}
	if id16 == nil {
		return uint8(0)
	}
	v45 := (vlen > 0) && (val == nil)
	if v45 {
		return uint8(0)
	}
	if bt_read8(heap[v21:], n, (base+20)) != 1 {
		return uint8(0)
	}
	for v9 = 0; v9 < uint64(bt_read16(heap[v21:], n, (base+22))); v9++ {
		v62 := uint64(64) + (v9 * 2)
		if bt_off_ok(n, base, v62, uint64(2)) == 0 {
			return uint8(0)
		}
		v70 := uint64(bt_read16(heap[v21:], n, (base + v62)))
		if bt_off_ok(n, base, v70, uint64(4)) == 0 {
			return uint8(0)
		}
		v75 := heap[v21:]
		v76 := base + v70
		v14 = bt_read16(v75[:], n, v76)
		v15 = bt_read16(v75[:], n, (v76 + 2))
		if bt_off_ok(n, base, v70, (((uint64(4)+uint64(v14))+16)+uint64(v15))) == 0 {
			return uint8(0)
		}
		v102 = (uint64(v14) == klen) && (bt_keyeq(heap[v21:], n, ((base+v70)+4), klen, key[:]) != 0)
		if v102 {
			if v17 == 0 {
				v12 = v70
				v17 = 1
			} else {
				v109 = uint64(v14)
				if bt_keycmp_pp(heap[v21:], n, (((base+v70)+4)+v109), uint64(16), (((base+v12)+4)+v109), uint64(16)) > 0 {
					v12 = v70
				}
			}
		}
	}
	if v17 == 0 {
		return uint8(0)
	}
	v124 := heap[v21:]
	v125 := base + v12
	v14 = bt_read16(v124[:], n, v125)
	v15 = bt_read16(v124[:], n, (v125 + 2))
	if uint64(v15) != vlen {
		return uint8(0)
	}
	if bt_off_ok(n, base, v12, (((uint64(4)+uint64(v14))+16)+uint64(v15))) == 0 {
		return uint8(0)
	}
	v157 := (vlen > 0) && (bt_keycmp_at(heap[v21:], n, ((((base+v12)+4)+uint64(v14))+16), vlen, val[:], vlen) != 0)
	if v157 {
		return uint8(0)
	}
	bt_copy_in(heap[v21:], n, (base + ((v12 + 4) + uint64(v14))), id16[v21:], uint64(16))
	return uint8(1)
}

func bt_insert_ver_at(heap []byte, n uint64, base uint64, key []byte, klen uint64, id16 []byte, val []byte, vlen uint64) Db_bt_state_t {
	var v9 uint64
	var v16 uint64
	v21 := uint64(0)
	var v8 Db_bt_state_t
	v8.Nkeys = 0
	v8.Ok = 0
	v8.Copied = 0
	if heap == nil {
		return v8
	}
	if ((klen == 0) || (klen > 0xffff)) || (vlen > 0xffff) {
		return v8
	}
	if (key == nil) || (id16 == nil) {
		return v8
	}
	v41 := (vlen > 0) && (val == nil)
	if v41 {
		return v8
	}
	if bt_read8(heap[v21:], n, (base+20)) != 1 {
		return v8
	}
	v47 := heap[v21:]
	v9 = uint64(bt_read16(v47[:], n, (base + 22)))
	v56 := uint64(bt_read16(v47[:], n, (base + 24)))
	v61 := uint64(bt_read16(v47[:], n, (base + 26)))
	v8.Nkeys = v9
	if v56 < 64 {
		return v8
	}
	if v61 > 0x4000 {
		return v8
	}
	if v56 > v61 {
		return v8
	}
	v68 := ((uint64(4) + klen) + 16) + vlen
	if v56 >= 0x4000 {
		return v8
	}
	if 2 > (uint64(0x4000) - v56) {
		return v8
	}
	v74 := v56 + 2
	if v68 > v61 {
		return v8
	}
	v75 := v61 - v68
	if v74 > v75 {
		return v8
	}
	if bt_off_ok(n, base, v75, v68) == 0 {
		return v8
	}
	v16 = bt_find_ver_pos_at(heap[v21:], n, base, key[:], klen, id16[:])
	if v16 > v9 {
		v16 = v9
	}
	v80 := heap[v21:]
	v81 := base + v75
	bt_write16(v80[:], n, v81, uint16(klen))
	bt_write16(v80[:], n, (v81 + 2), uint16(vlen))
	v93 := v81 + 4
	bt_copy_in(v80[:], n, v93, key[:], klen)
	bt_copy_in(v80[:], n, (v93 + klen), id16[:], uint64(16))
	if vlen > 0 {
		bt_copy_in(heap[v21:], n, ((((base + v75) + 4) + klen) + 16), val[:], vlen)
	}
	v111 := heap[v21:]
	v112 := uint16(v75)
	bt_slot_insert_at(v111[:], n, base, v16, v9, v112)
	v9++
	bt_write16(v111[:], n, (base + 22), uint16(v9))
	bt_write16(v111[:], n, (base + 24), uint16(v74))
	bt_write16(v111[:], n, (base + 26), v112)
	v8.Nkeys = v9
	v8.Ok = 1
	return v8
}

func bt_get_as_of_at(heap []byte, n uint64, base uint64, key []byte, klen uint64, snap16 []byte, out []byte, outn uint64) Db_bt_get_t {
	var v10 uint64
	var v13 uint64
	var v14 uint64
	var v15 uint64
	var v16 uint16
	var v17 uint16
	var v19 byte
	var v21 int32
	v29 := uint64(0)
	var v8 Db_bt_get_t
	v8.Len_ = 0
	v8.Walked = 0
	v8.Found = 0
	v8.Fallback = 0
	v13 = v29
	v14 = v13
	v19 = 0
	if heap == nil {
		return v8
	}
	if (((key == nil) || (snap16 == nil)) || (klen == 0)) || (klen > 0xffff) {
		return v8
	}
	if bt_read8(heap[v29:], n, (base+20)) != 1 {
		return v8
	}
	for v10 = 0; v10 < uint64(bt_read16(heap[v29:], n, (base+22))); v10++ {
		v57 := uint64(64) + (v10 * 2)
		if bt_off_ok(n, base, v57, uint64(2)) == 0 {
			return v8
		}
		v64 := uint64(bt_read16(heap[v29:], n, (base + v57)))
		if bt_off_ok(n, base, v64, uint64(4)) == 0 {
			return v8
		}
		v68 := heap[v29:]
		v69 := base + v64
		v16 = bt_read16(v68[:], n, v69)
		v17 = bt_read16(v68[:], n, (v69 + 2))
		if bt_off_ok(n, base, v64, (((uint64(4)+uint64(v16))+16)+uint64(v17))) == 0 {
			return v8
		}
		v90 := bt_keycmp_at(heap[v29:], n, ((base + v64) + 4), uint64(v16), key[:], klen)
		if v90 > 0 {
			break
		}
		if v90 == 0 {
			v21 = bt_keycmp_at(heap[v29:], n, (((base + v64) + 4) + uint64(v16)), uint64(16), snap16[:], uint64(16))
			if v21 <= 0 {
				if v19 == 0 {
					v13 = v64
					v14 = ((base + v64) + 4) + uint64(v16)
					v19 = 1
				} else {
					v21 = bt_keycmp_pp(heap[v29:], n, (((base + v64) + 4) + uint64(v16)), uint64(16), v14, uint64(16))
					if v21 > 0 {
						v13 = v64
						v14 = ((base + v64) + 4) + uint64(v16)
					}
				}
			}
		}
	}
	if v19 == 0 {
		return v8
	}
	v128 := heap[v29:]
	v129 := base + v13
	v16 = bt_read16(v128[:], n, v129)
	v17 = bt_read16(v128[:], n, (v129 + 2))
	v136 := uint64(v17)
	v8.Len_ = v136
	v8.Found = 1
	v15 = v136
	if v15 > outn {
		v15 = outn
	}
	v145 := (out != nil) && (v15 > 0)
	if v145 {
		bt_copy_out(heap[v29:], n, ((((base + v13) + 4) + uint64(v16)) + 16), out[v29:], v15)
	}
	return v8
}

func bt_insert_ver_heap_impl(pub []byte, dirty []byte, nbytes uint64, npages uint64, st *Db_bt_heap_st_t, key []byte, klen uint64, id16 []byte, val []byte, vlen uint64, prune uint64) Db_bt_heap_st_t {
	var v14 uint64
	var v15 uint64
	var v16 uint64
	var v17 uint64
	var v18 uint64
	var v19 uint64
	var v20 uint64
	var v21 uint64
	var v22 uint64
	var v23 uint64
	var v24 uint64
	var v26 byte
	var v27 int32
	var v29 uint64
	var v86 bool
	var v111 bool
	var v131 uint64
	var v150 uint64
	var v182 uint64
	var v190 uint64
	var v229 bool
	var v11 Db_bt_heap_st_t
	var v12 Db_bt_state_t
	var v13 Db_bt_get_t
	var v28 [32]uint64
	var v30 Db_bt_heap_st_t
	v11.Root = 0
	v11.Used = 0
	v11.Nkeys = 0
	v11.Pages = 0
	v11.Ok = 0
	v11.Full = 0
	v29 = 0
	if (pub == nil) || (dirty == nil) {
		return v11
	}
	if npages == 0 {
		return v11
	}
	if (nbytes / 0x4000) != npages {
		return v11
	}
	if (npages * 0x4000) != nbytes {
		return v11
	}
	v23 = 0
	if ((klen == 0) || (klen > 0xffff)) || (vlen > 0xffff) {
		return v11
	}
	if (key == nil) || (id16 == nil) {
		return v11
	}
	v66 := (vlen > 0) && (val == nil)
	if v66 {
		return v11
	}
	v17 = st.Used
	if v17 == 0 {
		v17 = 1
	}
	if st.Root >= npages {
		return v11
	}
	v14 = st.Root
	st.Root = v14
	v24 = st.Root
	v23 = bt_cow_page(pub[:], dirty[:], nbytes, v14, v23)
	v19 = v14 * 0x4000
	v26 = bt_read8(dirty[:], nbytes, (v19 + 20))
	if v26 == 2 {
		v28[0] = v14
		v29 = 1
		v15 = 0
		for {
			v86 = (v26 == 2) && (v15 < npages)
			if !v86 {
				break
			}
			v24 = v14
			v87 := bt_internal_child(dirty[:], nbytes, v19, key[:], klen)
			if v87 >= npages {
				return v11
			}
			if v87 == v14 {
				return v11
			}
			v14 = v87
			v23 = bt_cow_page(pub[:], dirty[:], nbytes, v14, v23)
			v19 = v14 * 0x4000
			v26 = bt_read8(dirty[:], nbytes, (v19 + 20))
			v15++
			if v26 == 2 {
				if v29 >= 32 {
					return v11
				}
				v28[v29] = v14
				v29++
			}
		}
		if v26 == 2 {
			return v11
		}
		v13 = bt_get_at(dirty[:], nbytes, v19, key[:], klen, nil, uint64(0))
		if v13.Found != 0 {
			v111 = (prune != 0) && (bt_replace_same_value_at(dirty[:], nbytes, v19, key[:], klen, id16[:], val[:], vlen) != 0)
			if v111 {
				v11.Root = st.Root
				v11.Used = v17
				v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
				v11.Pages = v23
				v11.Ok = 1
				return v11
			}
			v12 = bt_insert_ver_at(dirty[:], nbytes, v19, key[:], klen, id16[:], val[:], vlen)
			if v12.Ok != 0 {
				v11.Root = st.Root
				v11.Used = v17
				v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
				v11.Pages = v23
				v11.Ok = 1
				return v11
			}
		}
		v12 = bt_insert_ver_at(dirty[:], nbytes, v19, key[:], klen, id16[:], val[:], vlen)
		if v12.Ok != 0 {
			v11.Root = st.Root
			v11.Used = v17
			v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
			v11.Pages = v23
			v11.Ok = 1
			return v11
		}
		v131 = v17 + 2
		if (v131 > npages) || (v131 < v17) {
			v11.Full = 1
			return v11
		}
		v23 = bt_cow_page(pub[:], dirty[:], nbytes, v17, v23)
		if bt_chain_split_ver(dirty[:], npages, v14, v17) == 0 {
			return v11
		}
		v19 = v17 * 0x4000
		v21 = uint64(bt_read16(dirty[:], nbytes, (v19 + 64)))
		if bt_off_ok(nbytes, v19, v21, uint64(4)) == 0 {
			return v11
		}
		v150 = v19 + v21
		v22 = uint64(bt_read16(dirty[:], nbytes, v150))
		v27 = bt_keycmp_at(dirty[:], nbytes, (v150 + 4), v22, key[:], klen)
		if v27 > 0 {
			v19 = v14 * 0x4000
			v12 = bt_insert_ver_at(dirty[:], nbytes, v19, key[:], klen, id16[:], val[:], vlen)
		} else {
			v19 = v17 * 0x4000
			v12 = bt_insert_ver_at(dirty[:], nbytes, v19, key[:], klen, id16[:], val[:], vlen)
		}
		if v12.Ok == 0 {
			return v11
		}
		if bt_internal_add_sep(dirty[:], nbytes, npages, v24, v14, v17) != 0 {
			v11.Root = st.Root
			v11.Used = v17 + 1
			v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
			v11.Pages = v23
			v11.Ok = 1
			return v11
		}
		v20 = v17 + 1
		if v24 == st.Root {
			if (v20 + 1) >= npages {
				v11.Full = 1
				return v11
			}
			v23 = bt_cow_page(pub[:], dirty[:], nbytes, v20, v23)
			v182 = v20 + 1
			v23 = bt_cow_page(pub[:], dirty[:], nbytes, v182, v23)
			if bt_elevate_root(dirty[:], nbytes, npages, st.Root, v20, v182, v14, v17) == 0 {
				return v11
			}
			v190 = v20 + 1
			v11.Root = v190
			v11.Used = v17 + 3
			v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, v190)
			v11.Pages = v23
			v11.Ok = 1
			return v11
		}
		if v20 >= npages {
			v11.Full = 1
			return v11
		}
		v23 = bt_cow_page(pub[:], dirty[:], nbytes, v20, v23)
		v30 = bt_split_attach_deep(pub[:], dirty[:], nbytes, npages, v28[:], (v29 - 1), st.Root, (v17 + 2), v23, v24, v20, v14, v17)
		if v30.Ok == 0 {
			v11.Full = v30.Full
			return v11
		}
		v11.Root = v30.Root
		v11.Used = v30.Used
		v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, v30.Root)
		v11.Pages = v30.Pages
		v11.Ok = 1
		return v11
	}
	v14 = st.Root
	v15 = 0
	v18 = v14
	for v15 < npages {
		if v14 >= npages {
			return v11
		}
		v23 = bt_cow_page(pub[:], dirty[:], nbytes, v14, v23)
		v19 = v14 * 0x4000
		v13 = bt_get_at(dirty[:], nbytes, v19, key[:], klen, nil, uint64(0))
		if v13.Found != 0 {
			v229 = (prune != 0) && (bt_replace_same_value_at(dirty[:], nbytes, v19, key[:], klen, id16[:], val[:], vlen) != 0)
			if v229 {
				v11.Root = st.Root
				v11.Used = v17
				v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
				v11.Pages = v23
				v11.Ok = 1
				return v11
			}
			v12 = bt_insert_ver_at(dirty[:], nbytes, v19, key[:], klen, id16[:], val[:], vlen)
			if v12.Ok != 0 {
				v11.Root = st.Root
				v11.Used = v17
				v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
				v11.Pages = v23
				v11.Ok = 1
				return v11
			}
			v18 = v14
			break
		}
		v18 = v14
		v16 = bt_read64(dirty[:], nbytes, (v19 + 8))
		if v16 == 0 {
			break
		}
		if v16 == v14 {
			break
		}
		v14 = v16
		v15++
	}
	v14 = st.Root
	for v15 = 0; v15 < npages; v15++ {
		if v14 >= npages {
			break
		}
		v23 = bt_cow_page(pub[:], dirty[:], nbytes, v14, v23)
		v19 = v14 * 0x4000
		v12 = bt_insert_ver_at(dirty[:], nbytes, v19, key[:], klen, id16[:], val[:], vlen)
		if v12.Ok != 0 {
			v11.Root = st.Root
			v11.Used = v17
			v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
			v11.Pages = v23
			v11.Ok = 1
			return v11
		}
		v18 = v14
		v16 = bt_read64(dirty[:], nbytes, (v19 + 8))
		if v16 == 0 {
			break
		}
		if v16 == v14 {
			break
		}
		v14 = v16
	}
	if v18 != st.Root {
		return v11
	}
	if v17 >= npages {
		return v11
	}
	v269 := v17 + 2
	v275 := (npages > 2) && ((v269 > npages) || (v269 < v17))
	if v275 {
		return v11
	}
	v23 = bt_cow_page(pub[:], dirty[:], nbytes, v18, v23)
	v23 = bt_cow_page(pub[:], dirty[:], nbytes, v17, v23)
	if bt_chain_split_ver(dirty[:], npages, v18, v17) == 0 {
		return v11
	}
	v19 = v17 * 0x4000
	v21 = uint64(bt_read16(dirty[:], nbytes, (v19 + 64)))
	if bt_off_ok(nbytes, v19, v21, uint64(4)) == 0 {
		return v11
	}
	v289 := v19 + v21
	v22 = uint64(bt_read16(dirty[:], nbytes, v289))
	v27 = bt_keycmp_at(dirty[:], nbytes, (v289 + 4), v22, key[:], klen)
	if v27 > 0 {
		v19 = v18 * 0x4000
		v12 = bt_insert_ver_at(dirty[:], nbytes, v19, key[:], klen, id16[:], val[:], vlen)
	} else {
		v19 = v17 * 0x4000
		v12 = bt_insert_ver_at(dirty[:], nbytes, v19, key[:], klen, id16[:], val[:], vlen)
	}
	if v12.Ok == 0 {
		return v11
	}
	v20 = v17 + 1
	if v20 < npages {
		v23 = bt_cow_page(pub[:], dirty[:], nbytes, v20, v23)
		if bt_make_internal(dirty[:], nbytes, npages, st.Root, v17, v20) == 0 {
			return v11
		}
		v11.Root = v20
		v11.Used = v17 + 2
		v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, v20)
		v11.Pages = v23
		v11.Ok = 1
		return v11
	}
	if npages == 2 {
		v11.Root = st.Root
		v11.Used = v17 + 1
		v11.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
		v11.Pages = v23
		v11.Ok = 1
		return v11
	}
	return v11
}

func Db_bt_insert_ver_heap(pub []byte, dirty []byte, nbytes uint64, npages uint64, st *Db_bt_heap_st_t, key []byte, klen uint64, id16 []byte, val []byte, vlen uint64) Db_bt_heap_st_t {
	return bt_insert_ver_heap_impl(pub[:], dirty[:], nbytes, npages, st, key[:], klen, id16[:], val[:], vlen, uint64(0))
}

func Db_bt_insert_ver_heap_prune(pub []byte, dirty []byte, nbytes uint64, npages uint64, st *Db_bt_heap_st_t, key []byte, klen uint64, id16 []byte, val []byte, vlen uint64, prune uint64) Db_bt_heap_st_t {
	return bt_insert_ver_heap_impl(pub[:], dirty[:], nbytes, npages, st, key[:], klen, id16[:], val[:], vlen, prune)
}

func Db_bt_get_as_of_heap(heap []byte, nbytes uint64, npages uint64, root uint64, key []byte, klen uint64, snap16 []byte, out []byte, outn uint64) Db_bt_get_t {
	var v10 uint64
	var v11 uint64
	var v13 uint64
	var v15 byte
	var v9 Db_bt_get_t
	v9.Len_ = 0
	v9.Walked = 0
	v9.Found = 0
	v9.Fallback = 0
	if (heap == nil) || (npages == 0) {
		return v9
	}
	if (nbytes / 0x4000) != npages {
		return v9
	}
	if (npages * 0x4000) != nbytes {
		return v9
	}
	if (((key == nil) || (snap16 == nil)) || (klen == 0)) || (klen > 0xffff) {
		return v9
	}
	v10 = root
	v11 = 0
	if v10 >= npages {
		return v9
	}
	v13 = v10 * 0x4000
	v15 = bt_read8(heap[:], nbytes, (v13 + 20))
	for {
		v49 := (v15 == 2) && (v11 < npages)
		if !v49 {
			break
		}
		v50 := bt_internal_child(heap[:], nbytes, v13, key[:], klen)
		if v50 >= npages {
			v9.Walked = v11 + 1
			return v9
		}
		if v50 == v10 {
			v9.Walked = v11 + 1
			return v9
		}
		v10 = v50
		v11++
		v13 = v10 * 0x4000
		v15 = bt_read8(heap[:], nbytes, (v13 + 20))
	}
	if v15 == 2 {
		v9.Walked = v11
		return v9
	}
	if v11 != 0 {
		v9 = bt_get_as_of_at(heap[:], nbytes, v13, key[:], klen, snap16[:], out[:], outn)
		v9.Walked = v11 + 1
		v9.Fallback = 0
		return v9
	}
	for v11 < npages {
		if v10 >= npages {
			v9.Walked = v11
			return v9
		}
		v13 = v10 * 0x4000
		v9 = bt_get_as_of_at(heap[:], nbytes, v13, key[:], klen, snap16[:], out[:], outn)
		if v9.Found != 0 {
			v9.Walked = v11 + 1
			v9.Fallback = 0
			return v9
		}
		v78 := bt_read64(heap[:], nbytes, (v13 + 8))
		if v78 == 0 {
			v9.Walked = v11 + 1
			v9.Fallback = 0
			return v9
		}
		if v78 == v10 {
			v9.Walked = v11 + 1
			v9.Fallback = 0
			return v9
		}
		v10 = v78
		v11++
	}
	v9.Walked = v11
	v9.Fallback = 0
	return v9
}

func bt_del_at(heap []byte, n uint64, base uint64, key []byte, klen uint64) byte {
	var v6 uint64
	var v7 uint64
	var v13 byte
	var v75 bool
	v14 := uint64(0)
	if heap == nil {
		return uint8(0)
	}
	if ((key == nil) || (klen == 0)) || (klen > 0xffff) {
		return uint8(0)
	}
	if bt_read8(heap[v14:], n, (base+20)) != 1 {
		return uint8(0)
	}
	v7 = 0
	v6 = v7
	v13 = 0
	for v6 < uint64(bt_read16(heap[v14:], n, (base+22))) {
		v44 := uint64(64) + (v6 * 2)
		if bt_off_ok(n, base, v44, uint64(2)) == 0 {
			return uint8(0)
		}
		v51 := bt_read16(heap[v14:], n, (base + v44))
		v52 := uint64(v51)
		if bt_off_ok(n, base, v52, uint64(4)) == 0 {
			return uint8(0)
		}
		v59 := bt_read16(heap[v14:], n, (base + v52))
		if bt_off_ok(n, base, v52, (uint64(4)+uint64(v59))) == 0 {
			return uint8(0)
		}
		v75 = (uint64(v59) == klen) && (bt_keyeq(heap[v14:], n, ((base+v52)+4), klen, key[:]) != 0)
		if v75 {
			v13 = 1
		} else {
			if v7 != v6 {
				bt_write16(heap[v14:], n, ((base + 64) + (v7 * 2)), v51)
			}
			v7++
		}
		v6++
	}
	v88 := heap[v14:]
	bt_write16(v88[:], n, (base + 22), uint16(v7))
	bt_write16(v88[:], n, (base + 24), uint16(uint64(64)+(v7*2)))
	return v13
}

func Db_bt_del_heap(pub []byte, dirty []byte, nbytes uint64, npages uint64, st *Db_bt_heap_st_t, key []byte, klen uint64) Db_bt_heap_st_t {
	var v8 uint64
	var v9 uint64
	var v10 uint64
	var v14 uint64
	var v54 uint64
	v37 := uint64(0)
	var v7 Db_bt_heap_st_t
	v7.Root = 0
	v7.Used = 0
	v7.Nkeys = 0
	v7.Pages = 0
	v7.Ok = 0
	v7.Full = 0
	v14 = v37
	if (pub == nil) || (dirty == nil) {
		return v7
	}
	if npages == 0 {
		return v7
	}
	if (nbytes / 0x4000) != npages {
		return v7
	}
	if (npages * 0x4000) != nbytes {
		return v7
	}
	if (klen == 0) || (klen > 0xffff) {
		return v7
	}
	if key == nil {
		return v7
	}
	v10 = st.Used
	if v10 == 0 {
		v10 = 1
	}
	if st.Root >= npages {
		return v7
	}
	v8 = st.Root
	v9 = 0
	for v9 < npages {
		if v8 >= npages {
			return v7
		}
		v14 = bt_cow_page(pub[:], dirty[:], nbytes, v8, v14)
		v48 := v8 * 0x4000
		v51 := bt_read8(dirty[:], nbytes, (v48 + 20))
		if v51 == 2 {
			v54 = bt_internal_child(dirty[:], nbytes, v48, key[v37:], klen)
			if v54 >= npages {
				return v7
			}
			if v54 == v8 {
				return v7
			}
			v8 = v54
			v9++
		} else {
			if v51 == 1 {
				bt_del_at(dirty[:], nbytes, v48, key[v37:], klen)
				break
			} else {
				return v7
			}
		}
	}
	v7.Root = st.Root
	v7.Used = v10
	v7.Nkeys = bt_heap_nkeys(dirty[:], nbytes, npages, st.Root)
	v7.Pages = v14
	v7.Ok = 1
	return v7
}

func Db_bt_leaf_has_prefix(page []byte, n uint64, pref []byte, plen uint64) byte {
	var v5 uint64
	var v73 int
	v10 := uint64(0)
	if (page == nil) || (n != 0x4000) {
		return uint8(0)
	}
	if ((pref == nil) || (plen == 0)) || (plen > 0xffff) {
		return uint8(0)
	}
	if bt_read8(page[v10:], n, uint64(20)) != 1 {
		return uint8(0)
	}
	v5 = 0
	for v5 < uint64(bt_read16(page[v10:], n, uint64(22))) {
		v40 := uint64(64) + (v5 * 2)
		if bt_bounds(page[v10:], n, v40, uint64(2)) == 0 {
			return uint8(0)
		}
		v46 := page[v10:]
		v48 := uint64(bt_read16(v46[:], n, v40))
		if bt_bounds(v46[:], n, v48, uint64(4)) == 0 {
			return uint8(0)
		}
		v55 := bt_read16(page[v10:], n, v48)
		if uint64(v55) < plen {
			v5++
			continue
		}
		if bt_bounds(page[v10:], n, v48, (uint64(4)+uint64(v55))) == 0 {
			return uint8(0)
		}
		v73 = func(a, b []byte, n int) int {
			for i := 0; i < n && i < len(a) && i < len(b); i++ {
				if a[i] != b[i] {
					if a[i] < b[i] {
						return -1
					}
					return 1
				}
			}
			return 0
		}(page[int((v10+v48)+4):], pref[:], int(plen))
		if v73 == 0 {
			return uint8(1)
		}
		v5++
	}
	return uint8(0)
}

func Db_bt_merge_u64(a []uint64, na uint64, b []uint64, nb uint64, out []uint64, cap_ uint64) uint64 {
	var v6 uint64
	var v7 uint64
	var v8 uint64
	v6 = 0
	v7 = v6
	v8 = v7
	if ((a == nil) || (b == nil)) || (out == nil) {
		return 0
	}
	for {
		v23 := (v6 < na) && (v7 < nb)
		v25 := v23 && (v8 < cap_)
		if !v25 {
			break
		}
		if a[v6] < b[v7] {
			out[v8] = a[v6]
			v6++
			v8++
		} else {
			if b[v7] < a[v6] {
				out[v8] = b[v7]
				v7++
				v8++
			} else {
				out[v8] = a[v6]
				v6++
				v7++
				v8++
			}
		}
	}
	for {
		v49 := (v6 < na) && (v8 < cap_)
		if !v49 {
			break
		}
		out[v8] = a[v6]
		v6++
		v8++
	}
	for {
		v57 := (v7 < nb) && (v8 < cap_)
		if !v57 {
			break
		}
		out[v8] = b[v7]
		v7++
		v8++
	}
	return v8
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	Bt_bounds_IRCost                   = uint64(17)
	Bt_read8_IRCost                    = uint64(15)
	Bt_read16_IRCost                   = uint64(24)
	Bt_write8_IRCost                   = uint64(11)
	Bt_write16_IRCost                  = uint64(23)
	Bt_write32_IRCost                  = uint64(41)
	Bt_read64_IRCost                   = uint64(72)
	Bt_write64_IRCost                  = uint64(77)
	Bt_copy_bytes_IRCost               = uint64(24)
	Bt_cow_IRCost                      = uint64(9)
	Bt_cow_page_IRCost                 = uint64(37)
	Bt_copy_in_IRCost                  = uint64(19)
	Bt_copy_out_IRCost                 = uint64(19)
	Bt_keyeq_IRCost                    = uint64(29)
	Bt_keycmp_IRCost                   = uint64(37)
	Bt_keycmp_at_IRCost                = uint64(42)
	Bt_keycmp_pp_IRCost                = uint64(44)
	Bt_find_IRCost                     = uint64(38)
	Bt_off_ok_IRCost                   = uint64(24)
	Bt_find_at_IRCost                  = uint64(42)
	Bt_get_at_IRCost                   = uint64(108)
	Bt_insert_at_IRCost                = uint64(158)
	Db_bt_leaf_init_IRCost             = uint64(46)
	Db_bt_insert_IRCost                = uint64(138)
	Db_bt_get_IRCost                   = uint64(109)
	Bt_leaf_repack_IRCost              = uint64(170)
	Bt_chain_split_IRCost              = uint64(321)
	Bt_find_ver_pos_IRCost             = uint64(60)
	Bt_slot_insert_IRCost              = uint64(35)
	Bt_internal_child_IRCost           = uint64(65)
	Db_bt_child_of_IRCost              = uint64(35)
	Bt_make_internal_IRCost            = uint64(155)
	Bt_internal_insert_kv_IRCost       = uint64(203)
	Bt_internal_insert_buf_IRCost      = uint64(207)
	Bt_internal_add_sep_IRCost         = uint64(46)
	Bt_internal_has_child_IRCost       = uint64(78)
	Bt_elevate_root_IRCost             = uint64(314)
	Bt_split_internal_IRCost           = uint64(232)
	Bt_make_root_buf_IRCost            = uint64(121)
	Bt_split_attach_deep_IRCost        = uint64(141)
	Bt_heap_nkeys_IRCost               = uint64(51)
	Db_bt_get_heap_IRCost              = uint64(115)
	Db_bt_insert_heap_IRCost           = uint64(461)
	Db_bt_insert_ver_IRCost            = uint64(134)
	Db_bt_get_as_of_IRCost             = uint64(178)
	Db_bt_gc_before_IRCost             = uint64(107)
	Bt_keyhas_prefix_IRCost            = uint64(34)
	Bt_scan_prefix_at_IRCost           = uint64(126)
	Db_bt_scan_prefix_IRCost           = uint64(18)
	Db_bt_scan_prefix_heap_IRCost      = uint64(88)
	Bt_chain_split_ver_IRCost          = uint64(461)
	Bt_find_ver_pos_at_IRCost          = uint64(65)
	Bt_slot_insert_at_IRCost           = uint64(38)
	Bt_replace_same_value_at_IRCost    = uint64(191)
	Bt_insert_ver_at_IRCost            = uint64(155)
	Bt_get_as_of_at_IRCost             = uint64(186)
	Bt_insert_ver_heap_impl_IRCost     = uint64(493)
	Db_bt_insert_ver_heap_IRCost       = uint64(3)
	Db_bt_insert_ver_heap_prune_IRCost = uint64(2)
	Db_bt_get_as_of_heap_IRCost        = uint64(127)
	Bt_del_at_IRCost                   = uint64(116)
	Db_bt_del_heap_IRCost              = uint64(92)
	Db_bt_leaf_has_prefix_IRCost       = uint64(92)
	Db_bt_merge_u64_IRCost             = uint64(78)
)
