// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=e41586f1beaeb20445374017f9065c1188005f26c2ffed4dd770eb7cc0faac64
package c2db

type Db_wal_desc_t struct {
	Magic uint32
	Len_  uint32
	Typ   byte
	Plen  uint32
	Ok    byte
}

func Db_wal_bounds(block []byte, n uint64, addr uint64, len_ uint64) byte {
	var v14 bool
	if uint64(len(block)) < n {
		n = uint64(len(block))
	}
	if uint64(len(block)) < len_ {
		len_ = uint64(len(block))
	}
	_ = 0
	if block == nil {
		return uint8(0)
	}
	if n != 0x1000 {
		return uint8(0)
	}
	v14 = (addr < n) && (len_ <= (n - addr))
	if v14 {
		return uint8(1)
	}
	return uint8(0)
}

func Db_wal_type_ok(t byte) byte {
	switch t {
	case 0:
		return uint8(1)
	case 1:
		return uint8(1)
	case 2:
		return uint8(1)
	case 3:
		return uint8(1)
	case 4:
		return uint8(1)
	case 5:
		return uint8(1)
	case 6:
		return uint8(1)
	case 7:
		return uint8(1)
	case 8:
		return uint8(1)
	case 9:
		return uint8(1)
	default:
		return uint8(0)
	}
}

func Db_wal_payload_off() uint64 {
	return 25
}

func Db_wal_tag_off() uint64 {
	return 0xff0
}

func wal_read8(block []byte, n uint64, addr uint64) byte {
	var v11 bool
	if uint64(len(block)) < n {
		n = uint64(len(block))
	}
	if block == nil {
		return uint8(0)
	}
	v11 = (addr < n) && (1 <= (n - addr))
	if v11 {
		return byte(block[addr+0])
	}
	return uint8(0)
}

func wal_read32(block []byte, n uint64, addr uint64) uint32 {
	var v11 bool
	if uint64(len(block)) < n {
		n = uint64(len(block))
	}
	if block == nil {
		return 0
	}
	v11 = (addr < n) && (4 <= (n - addr))
	if v11 {
		return uint32(((uint32(block[addr+0]) | (uint32(block[addr+1+0]) << 8)) | (uint32(block[addr+2+0]) << 16)) | (uint32(block[addr+3+0]) << 24))
	}
	return 0
}

func wal_write8(block []byte, n uint64, addr uint64, val byte) {
	var v11 bool
	if uint64(len(block)) < n {
		n = uint64(len(block))
	}
	if block == nil {
		return
	}
	v11 = (addr < n) && (1 <= (n - addr))
	if v11 {
		block[addr+0] = val
	}
}

func wal_write32(block []byte, n uint64, addr uint64, val uint32) {
	var v4 uint64
	var v11 bool
	var v13 uint32
	var v19 uint64
	var v27 uint64
	var v35 uint64
	if uint64(len(block)) < n {
		n = uint64(len(block))
	}
	v4 = 0
	if block == nil {
		return
	}
	v11 = (addr < n) && (4 <= (n - addr))
	if v11 {
		v13 = val & 0xff
		block[v4+addr] = byte(v13)
		v19 = uint64(uint64(val)>>8) & 0xff
		block[v4+addr+1] = byte(v19)
		v27 = uint64(uint64(val)>>16) & 0xff
		block[v4+addr+2] = byte(v27)
		v35 = uint64(uint64(val)>>24) & 0xff
		block[v4+addr+3] = byte(v35)
	}
}

func wal_copy16_in(block []byte, n uint64, addr uint64, src []byte) {
	var v4 uint64
	var v14 bool
	if (block == nil) || (src == nil) {
		return
	}
	v14 = (addr < n) && (16 <= (n - addr))
	if v14 {
		for v4 = 0; v4 < 16; v4++ {
			block[addr+v4] = src[v4]
		}
	}
}

func wal_copy16_out(block []byte, n uint64, addr uint64, dst []byte) {
	var v4 uint64
	var v14 bool
	if (block == nil) || (dst == nil) {
		return
	}
	v14 = (addr < n) && (16 <= (n - addr))
	if v14 {
		for v4 = 0; v4 < 16; v4++ {
			dst[v4] = block[addr+v4]
		}
	}
}

func Db_wal_pack(block []byte, n uint64, id []byte, typ byte, payload []byte, plen uint64) byte {
	var v6 uint64
	var v9 uint64
	var v30 bool
	var v67 uint64
	var v72 bool
	var v84 bool
	v9 = 0
	if (block == nil) || (n != 0x1000) {
		return uint8(0)
	}
	if id == nil {
		return uint8(0)
	}
	if Db_wal_type_ok(typ) == 0 {
		return uint8(0)
	}
	if plen > 0xfd7 {
		return uint8(0)
	}
	v30 = (plen > 0) && (payload == nil)
	if v30 {
		return uint8(0)
	}
	if Db_wal_bounds(block[v9:], n, uint64(0), uint64(4)) == 0 {
		return uint8(0)
	}
	if Db_wal_bounds(block[v9:], n, uint64(8), uint64(16)) == 0 {
		return uint8(0)
	}
	if Db_wal_bounds(block[v9:], n, uint64(24), uint64(1)) == 0 {
		return uint8(0)
	}
	v51 := block[v9:]
	wal_write32(v51[:], n, uint64(0), uint32(0x43324442))
	wal_write32(v51[:], n, uint64(4), uint32(plen))
	wal_copy16_in(v51[:], n, uint64(8), id[v9:])
	wal_write8(v51[:], n, uint64(24), typ)
	for v6 = 0; v6 < plen; v6++ {
		v67 = 25 + v6
		v72 = (v67 < n) && (1 <= (n - v67))
		if v72 {
			block[v9+v67] = payload[v6]
		}
	}
	for v6 = 25 + plen; v6 < 0xff0; v6++ {
		v84 = (v6 < n) && (1 <= (n - v6))
		if v84 {
			block[v9+v6] = 0
		}
	}
	return uint8(1)
}

func Db_wal_unpack(block []byte, n uint64, id []byte) Db_wal_desc_t {
	var v12 uint64
	v12 = 0
	var v3 Db_wal_desc_t
	v3.Magic = 0
	v3.Len_ = 0
	v3.Typ = 0
	v3.Plen = 0
	v3.Ok = 0
	if (block == nil) || (n != 0x1000) {
		return v3
	}
	if Db_wal_bounds(block[v12:], n, uint64(0), uint64(4)) == 0 {
		return v3
	}
	if Db_wal_bounds(block[v12:], n, uint64(0xff0), uint64(16)) == 0 {
		return v3
	}
	v31 := wal_read32(block[v12:], n, uint64(0))
	v32 := block[v12:]
	v34 := wal_read32(v32[:], n, uint64(4))
	v3.Magic = v31
	v3.Len_ = v34
	v3.Typ = wal_read8(v32[:], n, uint64(24))
	if v31 != 0x43324442 {
		return v3
	}
	if uint64(v34) > 0xfd7 {
		return v3
	}
	v3.Plen = v34
	if id != nil {
		wal_copy16_out(block[v12:], n, uint64(8), id[v12:])
	}
	v3.Ok = 1
	return v3
}

func Db_wal_tag_slot(block []byte, n uint64, src []byte, dst []byte) byte {
	var v4 uint64
	v4 = 0
	if (block == nil) || (n != 0x1000) {
		return uint8(0)
	}
	if Db_wal_bounds(block[v4:], n, uint64(0xff0), uint64(16)) == 0 {
		return uint8(0)
	}
	if src != nil {
		wal_copy16_in(block[v4:], n, uint64(0xff0), src[v4:])
	}
	if dst != nil {
		wal_copy16_out(block[v4:], n, uint64(0xff0), dst[v4:])
	}
	return uint8(1)
}
