//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=9c0644948a35d711a0a67a906a77aeb51fcbe372c5745a0ee9f81bfec6230de2
package c2db

import "simd/archsimd"

func Page4k_is_zero_avx2(page []byte, n uint64) byte {
	var v10 archsimd.Uint8x32
	var v12 uint64
	if (page == nil) || (n != 0x1000) {
		return uint8(0)
	}
	v10 = archsimd.BroadcastUint8x32(byte(0))
	for v12 = 0; v12 < 0x1000; v12 += 32 {
		v10 = v10.Or(archsimd.LoadUint8x32(page[int(uint64(0)+v12):][:32]))
	}
	return byte(boolToU8(v10.IsZero()))
}

func boolToU8(b bool) uint8 {
	if b {
		return 1
	}
	return 0
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const Page4k_is_zero_avx2_IRCost = uint64(28)
