//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=a3219298f65846025118a04c214f2af84446b3db38557f17e6572e4a2a6d8036
package blake3archtsim

import (
	"math/bits"
	"simd/archsimd"
)

var (
	BLAKE3ARCHTSIM_IV              = [8]uint32{0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A, 0x510E527F, 0x9B05688C, 0x1F83D9AB, 0x5BE0CD19}
	BLAKE3ARCHTSIM_MSG_PERMUTATION = [16]byte{2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8}
	BLAKE3ARCHTSIM_ROT16           = [16]byte{2, 3, 0, 1, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13}
	BLAKE3ARCHTSIM_ROT8            = [16]byte{1, 2, 3, 0, 5, 6, 7, 4, 9, 10, 11, 8, 13, 14, 15, 12}
)

func __avx2() int {
	v3 := func() int {
		if 1 != 0 {
			return 1
		}
		return 0
	}()
	return v3
}

func blake3archtsim_rotr32(w uint32, c uint32) uint32 {
	return bits.RotateLeft32(w, 32-int(c))
}

func blake3archtsim_g(state []uint32, a int, b int, c int, d int, mx uint32, my uint32) {
	state[a] = (state[a] + state[b]) + mx
	state[d] = blake3archtsim_rotr32((state[d] ^ state[a]), uint32(16))
	state[c] += state[d]
	state[b] = blake3archtsim_rotr32((state[b] ^ state[c]), uint32(12))
	state[a] = (state[a] + state[b]) + my
	state[d] = blake3archtsim_rotr32((state[d] ^ state[a]), uint32(8))
	state[c] += state[d]
	state[b] = blake3archtsim_rotr32((state[b] ^ state[c]), uint32(7))
}

func Blake3archtsim_compress_scalar(cv []uint32, block []byte, block_len byte, counter uint64, flags byte, out []uint32) {
	var v11 int
	var v12 int
	var v8 [16]uint32
	var v9 [16]uint32
	var v10 [16]uint32
	copy(v8[:8], cv[:8])
	for v11 = 0; v11 < 4; v11++ {
		v8[v11+8] = uint32(BLAKE3ARCHTSIM_IV[v11])
	}
	v8[12] = uint32(counter)
	v8[13] = uint32(uint64(counter >> 32))
	v8[14] = uint32(block_len)
	v8[15] = uint32(flags)
	for v11 = 0; v11 < 16; v11++ {
		v40 := v11 * 4
		v9[v11] = ((uint32(block[v40]) | uint32(uint32(block[(v40+1)])<<8)) | uint32(uint32(block[(v40+2)])<<16)) | uint32(uint32(block[(v40+3)])<<24)
	}
	for v12 = 0; v12 < 7; v12++ {
		blake3archtsim_g(v8[:], 0, 4, 8, 12, v9[0], v9[1])
		blake3archtsim_g(v8[:], 1, 5, 9, 13, v9[2], v9[3])
		blake3archtsim_g(v8[:], 2, 6, 10, 14, v9[4], v9[5])
		blake3archtsim_g(v8[:], 3, 7, 11, 15, v9[6], v9[7])
		blake3archtsim_g(v8[:], 0, 5, 10, 15, v9[8], v9[9])
		blake3archtsim_g(v8[:], 1, 6, 11, 12, v9[10], v9[11])
		blake3archtsim_g(v8[:], 2, 7, 8, 13, v9[12], v9[13])
		blake3archtsim_g(v8[:], 3, 4, 9, 14, v9[14], v9[15])
		v11 = 0
		for v11 < 16 {
			v10[v11] = v9[int(BLAKE3ARCHTSIM_MSG_PERMUTATION[v11])]
			v11++
		}
		copy(v9[:16], v10[:16])
	}
	for v11 = 0; v11 < 8; v11++ {
		v163 := v11 + 8
		v164 := v8[v163]
		out[v11] = v8[v11] ^ v164
		out[v163] = v164 ^ cv[v11]
	}
}

func Blake3archtsim_compress_avx2(cv []uint32, block []byte, block_len byte, counter uint64, flags byte, out []uint32) {
	var v14 archsimd.Uint8x16
	var v15 archsimd.Uint8x16
	var v16 archsimd.Uint8x16
	var v17 archsimd.Uint8x16
	var v18 archsimd.Uint8x16
	var v19 archsimd.Uint8x16
	var v20 archsimd.Uint8x16
	var v23 int
	var v24 int
	var v21 [16]uint32
	var v22 [16]uint32
	v26 := archsimd.LoadUint8x16(BLAKE3ARCHTSIM_ROT16[0:16])
	v28 := archsimd.LoadUint8x16(BLAKE3ARCHTSIM_ROT8[0:16])
	for v23 = 0; v23 < 16; v23++ {
		v34 := v23 * 4
		v21[v23] = ((uint32(block[v34]) | uint32(uint32(block[(v34+1)])<<8)) | uint32(uint32(block[(v34+2)])<<16)) | uint32(uint32(block[(v34+3)])<<24)
	}
	v68 := archsimd.LoadUint32x4(cv[:4]).AsUint8x16()
	v73 := archsimd.LoadUint32x4(cv[4:8]).AsUint8x16()
	v14 = v68
	v15 = v73
	v16 = archsimd.LoadUint32x4Array(&[4]uint32{uint32(1779033703), uint32(3144134277), uint32(1013904242), uint32(2773480762)}).AsUint8x16()
	v17 = archsimd.LoadUint32x4Array(&[4]uint32{uint32(counter), uint32(uint64(counter >> 32)), uint32(block_len), uint32(flags)}).AsUint8x16()
	for v24 = 0; v24 < 7; v24++ {
		v18 = archsimd.LoadUint32x4Array(&[4]uint32{uint32(v21[0]), uint32(v21[2]), uint32(v21[4]), uint32(v21[6])}).AsUint8x16()
		v19 = archsimd.LoadUint32x4Array(&[4]uint32{uint32(v21[1]), uint32(v21[3]), uint32(v21[5]), uint32(v21[7])}).AsUint8x16()
		v128 := v14.AsUint32x4().Add(v15.AsUint32x4()).AsUint8x16()
		v14 = v128.AsUint32x4().Add(v18.AsUint32x4()).AsUint8x16()
		v17 = v17.Xor(v14).PermuteOrZero(v26.AsInt8x16())
		v16 = v16.AsUint32x4().Add(v17.AsUint32x4()).AsUint8x16()
		v20 = v15.Xor(v16)
		v15 = v20.AsUint32x4().ShiftAllRight(12).AsUint8x16().Or(v20.AsUint32x4().ShiftAllLeft(20).AsUint8x16())
		v139 := v14.AsUint32x4().Add(v15.AsUint32x4()).AsUint8x16()
		v14 = v139.AsUint32x4().Add(v19.AsUint32x4()).AsUint8x16()
		v17 = v17.Xor(v14).PermuteOrZero(v28.AsInt8x16())
		v16 = v16.AsUint32x4().Add(v17.AsUint32x4()).AsUint8x16()
		v20 = v15.Xor(v16)
		v15 = v20.AsUint32x4().ShiftAllRight(7).AsUint8x16().Or(v20.AsUint32x4().ShiftAllLeft(25).AsUint8x16())
		v15 = v15.AsUint32x4().PermuteScalars(1, 2, 3, 0).AsUint8x16()
		v16 = v16.AsUint32x4().PermuteScalars(2, 3, 0, 1).AsUint8x16()
		v17 = v17.AsUint32x4().PermuteScalars(3, 0, 1, 2).AsUint8x16()
		v18 = archsimd.LoadUint32x4Array(&[4]uint32{uint32(v21[8]), uint32(v21[10]), uint32(v21[12]), uint32(v21[14])}).AsUint8x16()
		v19 = archsimd.LoadUint32x4Array(&[4]uint32{uint32(v21[9]), uint32(v21[11]), uint32(v21[13]), uint32(v21[15])}).AsUint8x16()
		v182 := v14.AsUint32x4().Add(v15.AsUint32x4()).AsUint8x16()
		v14 = v182.AsUint32x4().Add(v18.AsUint32x4()).AsUint8x16()
		v17 = v17.Xor(v14).PermuteOrZero(v26.AsInt8x16())
		v16 = v16.AsUint32x4().Add(v17.AsUint32x4()).AsUint8x16()
		v20 = v15.Xor(v16)
		v15 = v20.AsUint32x4().ShiftAllRight(12).AsUint8x16().Or(v20.AsUint32x4().ShiftAllLeft(20).AsUint8x16())
		v193 := v14.AsUint32x4().Add(v15.AsUint32x4()).AsUint8x16()
		v14 = v193.AsUint32x4().Add(v19.AsUint32x4()).AsUint8x16()
		v17 = v17.Xor(v14).PermuteOrZero(v28.AsInt8x16())
		v16 = v16.AsUint32x4().Add(v17.AsUint32x4()).AsUint8x16()
		v20 = v15.Xor(v16)
		v15 = v20.AsUint32x4().ShiftAllRight(7).AsUint8x16().Or(v20.AsUint32x4().ShiftAllLeft(25).AsUint8x16())
		v15 = v15.AsUint32x4().PermuteScalars(3, 0, 1, 2).AsUint8x16()
		v16 = v16.AsUint32x4().PermuteScalars(2, 3, 0, 1).AsUint8x16()
		v17 = v17.AsUint32x4().PermuteScalars(1, 2, 3, 0).AsUint8x16()
		v23 = 0
		for v23 < 16 {
			v22[v23] = v21[int(BLAKE3ARCHTSIM_MSG_PERMUTATION[v23])]
			v23++
		}
		copy(v21[:16], v22[:16])
	}
	v14.Xor(v16).AsUint32x4().Store(out[0:4])
	v15.Xor(v17).AsUint32x4().Store(out[4:8])
	v16.Xor(v68).AsUint32x4().Store(out[8:12])
	v17.Xor(v73).AsUint32x4().Store(out[12:16])
}

func Blake3archtsim_compress(cv []uint32, block []byte, block_len byte, counter uint64, flags byte, out []uint32) {
	if archsimd.X86.AVX2() {
		Blake3archtsim_compress_avx2(cv[:], block[:], block_len, counter, flags, out[:])
	} else {
		Blake3archtsim_compress_scalar(cv[:], block[:], block_len, counter, flags, out[:])
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	__avx2_IRCost                         = uint64(5)
	Blake3archtsim_rotr32_IRCost          = uint64(6)
	Blake3archtsim_g_IRCost               = uint64(42)
	Blake3archtsim_compress_scalar_IRCost = uint64(192)
	Blake3archtsim_compress_avx2_IRCost   = uint64(288)
	Blake3archtsim_compress_IRCost        = uint64(3)
)
