//go:build !goexperiment.simd || !amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=844568843265622abb9ee62752ba7f93e5bc186e3c8f0d20d98effe69c124a23
package blake3archtsim

import "math/bits"

var (
	BLAKE3ARCHTSIM_IV              = [8]uint32{0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A, 0x510E527F, 0x9B05688C, 0x1F83D9AB, 0x5BE0CD19}
	BLAKE3ARCHTSIM_MSG_PERMUTATION = [16]byte{2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8}
	BLAKE3ARCHTSIM_ROT16           = [16]byte{2, 3, 0, 1, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13}
	BLAKE3ARCHTSIM_ROT8            = [16]byte{1, 2, 3, 0, 5, 6, 7, 4, 9, 10, 11, 8, 13, 14, 15, 12}
)

func __avx2() int {
	v3 := func() int {
		if 1 != 0 {
			return 1
		}
		return 0
	}()
	return v3
}

func blake3archtsim_rotr32(w uint32, c uint32) uint32 {
	return bits.RotateLeft32(w, 32-int(c))
}

func blake3archtsim_g(state []uint32, a int, b int, c int, d int, mx uint32, my uint32) {
	state[a] = (state[a] + state[b]) + mx
	state[d] = blake3archtsim_rotr32((state[d] ^ state[a]), uint32(16))
	state[c] += state[d]
	state[b] = blake3archtsim_rotr32((state[b] ^ state[c]), uint32(12))
	state[a] = (state[a] + state[b]) + my
	state[d] = blake3archtsim_rotr32((state[d] ^ state[a]), uint32(8))
	state[c] += state[d]
	state[b] = blake3archtsim_rotr32((state[b] ^ state[c]), uint32(7))
}

func Blake3archtsim_compress_scalar(cv []uint32, block []byte, block_len byte, counter uint64, flags byte, out []uint32) {
	var v11 int
	var v12 int
	var v8 [16]uint32
	var v9 [16]uint32
	var v10 [16]uint32
	copy(v8[:8], cv[:8])
	for v11 = 0; v11 < 4; v11++ {
		v8[v11+8] = uint32(BLAKE3ARCHTSIM_IV[v11])
	}
	v8[12] = uint32(counter)
	v8[13] = uint32(uint64(counter >> 32))
	v8[14] = uint32(block_len)
	v8[15] = uint32(flags)
	for v11 = 0; v11 < 16; v11++ {
		v40 := v11 * 4
		v9[v11] = ((uint32(block[v40]) | uint32(uint32(block[(v40+1)])<<8)) | uint32(uint32(block[(v40+2)])<<16)) | uint32(uint32(block[(v40+3)])<<24)
	}
	for v12 = 0; v12 < 7; v12++ {
		blake3archtsim_g(v8[:], 0, 4, 8, 12, v9[0], v9[1])
		blake3archtsim_g(v8[:], 1, 5, 9, 13, v9[2], v9[3])
		blake3archtsim_g(v8[:], 2, 6, 10, 14, v9[4], v9[5])
		blake3archtsim_g(v8[:], 3, 7, 11, 15, v9[6], v9[7])
		blake3archtsim_g(v8[:], 0, 5, 10, 15, v9[8], v9[9])
		blake3archtsim_g(v8[:], 1, 6, 11, 12, v9[10], v9[11])
		blake3archtsim_g(v8[:], 2, 7, 8, 13, v9[12], v9[13])
		blake3archtsim_g(v8[:], 3, 4, 9, 14, v9[14], v9[15])
		v11 = 0
		for v11 < 16 {
			v10[v11] = v9[int(BLAKE3ARCHTSIM_MSG_PERMUTATION[v11])]
			v11++
		}
		copy(v9[:16], v10[:16])
	}
	for v11 = 0; v11 < 8; v11++ {
		v163 := v11 + 8
		v164 := v8[v163]
		out[v11] = v8[v11] ^ v164
		out[v163] = v164 ^ cv[v11]
	}
}

func Blake3archtsim_compress(cv []uint32, block []byte, block_len byte, counter uint64, flags byte, out []uint32) {
	Blake3archtsim_compress_scalar(cv[:], block[:], block_len, counter, flags, out[:])
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	__avx2_IRCost                         = uint64(5)
	Blake3archtsim_rotr32_IRCost          = uint64(6)
	Blake3archtsim_g_IRCost               = uint64(42)
	Blake3archtsim_compress_scalar_IRCost = uint64(192)
	Blake3archtsim_compress_IRCost        = uint64(1)
)
